// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

// MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder builds and executes requests for operations under \v2\monitoring\metrics\load_balancer\frontend_firewall_dropped_bytes
type MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderGetQueryParameters to retrieve firewall dropped bytes for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_bytes`. This is currently only supported for network load balancers.
type MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderGetQueryParameters struct {
    // UNIX timestamp to end metric window.
    End *string `uriparametername:"end"`
    // A unique identifier for a load balancer.
    Lb_id *string `uriparametername:"lb_id"`
    // UNIX timestamp to start metric window.
    Start *string `uriparametername:"start"`
}
// MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderGetQueryParameters
}
// NewMonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderInternal instantiates a new MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder and sets the default values.
func NewMonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder) {
    m := &MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_bytes?end={end}&lb_id={lb_id}&start={start}", pathParameters),
    }
    return m
}
// NewMonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder instantiates a new MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder and sets the default values.
func NewMonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderInternal(urlParams, requestAdapter)
}
// Get to retrieve firewall dropped bytes for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_bytes`. This is currently only supported for network load balancers.
// returns a Metricsable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder) Get(ctx context.Context, requestConfiguration *MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderGetRequestConfiguration)(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Metricsable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateMetricsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Metricsable), nil
}
// ToGetRequestInformation to retrieve firewall dropped bytes for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/frontend_firewall_dropped_bytes`. This is currently only supported for network load balancers.
// returns a *RequestInformation when successful
func (m *MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder when successful
func (m *MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder) WithUrl(rawUrl string)(*MonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder) {
    return NewMonitoringMetricsLoad_balancerFrontend_firewall_dropped_bytesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
