// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AccountKeysItemWithSsh_key_identifierPutRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // A human-readable display name for this key, used to easily identify the SSH keys when they are displayed.
    name *string
}
// NewAccountKeysItemWithSsh_key_identifierPutRequestBody instantiates a new AccountKeysItemWithSsh_key_identifierPutRequestBody and sets the default values.
func NewAccountKeysItemWithSsh_key_identifierPutRequestBody()(*AccountKeysItemWithSsh_key_identifierPutRequestBody) {
    m := &AccountKeysItemWithSsh_key_identifierPutRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAccountKeysItemWithSsh_key_identifierPutRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccountKeysItemWithSsh_key_identifierPutRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccountKeysItemWithSsh_key_identifierPutRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AccountKeysItemWithSsh_key_identifierPutRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AccountKeysItemWithSsh_key_identifierPutRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    return res
}
// GetName gets the name property value. A human-readable display name for this key, used to easily identify the SSH keys when they are displayed.
// returns a *string when successful
func (m *AccountKeysItemWithSsh_key_identifierPutRequestBody) GetName()(*string) {
    return m.name
}
// Serialize serializes information the current object
func (m *AccountKeysItemWithSsh_key_identifierPutRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AccountKeysItemWithSsh_key_identifierPutRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetName sets the name property value. A human-readable display name for this key, used to easily identify the SSH keys when they are displayed.
func (m *AccountKeysItemWithSsh_key_identifierPutRequestBody) SetName(value *string)() {
    m.name = value
}
type AccountKeysItemWithSsh_key_identifierPutRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetName()(*string)
    SetName(value *string)()
}
