// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Byoip_prefixesPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The region where the prefix is created
    region *string
    // The status of the BYOIP prefix
    status *string
    // The unique identifier for the BYOIP prefix
    uuid *string
}
// NewByoip_prefixesPostResponse instantiates a new Byoip_prefixesPostResponse and sets the default values.
func NewByoip_prefixesPostResponse()(*Byoip_prefixesPostResponse) {
    m := &Byoip_prefixesPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateByoip_prefixesPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateByoip_prefixesPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewByoip_prefixesPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Byoip_prefixesPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Byoip_prefixesPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["region"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRegion(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val)
        }
        return nil
    }
    res["uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUuid(val)
        }
        return nil
    }
    return res
}
// GetRegion gets the region property value. The region where the prefix is created
// returns a *string when successful
func (m *Byoip_prefixesPostResponse) GetRegion()(*string) {
    return m.region
}
// GetStatus gets the status property value. The status of the BYOIP prefix
// returns a *string when successful
func (m *Byoip_prefixesPostResponse) GetStatus()(*string) {
    return m.status
}
// GetUuid gets the uuid property value. The unique identifier for the BYOIP prefix
// returns a *string when successful
func (m *Byoip_prefixesPostResponse) GetUuid()(*string) {
    return m.uuid
}
// Serialize serializes information the current object
func (m *Byoip_prefixesPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("region", m.GetRegion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("status", m.GetStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("uuid", m.GetUuid())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Byoip_prefixesPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetRegion sets the region property value. The region where the prefix is created
func (m *Byoip_prefixesPostResponse) SetRegion(value *string)() {
    m.region = value
}
// SetStatus sets the status property value. The status of the BYOIP prefix
func (m *Byoip_prefixesPostResponse) SetStatus(value *string)() {
    m.status = value
}
// SetUuid sets the uuid property value. The unique identifier for the BYOIP prefix
func (m *Byoip_prefixesPostResponse) SetUuid(value *string)() {
    m.uuid = value
}
type Byoip_prefixesPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetRegion()(*string)
    GetStatus()(*string)
    GetUuid()(*string)
    SetRegion(value *string)()
    SetStatus(value *string)()
    SetUuid(value *string)()
}
