// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

// CdnEndpointsWithCdn_ItemRequestBuilder builds and executes requests for operations under \v2\cdn\endpoints\{cdn_id}
type CdnEndpointsWithCdn_ItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CdnEndpointsWithCdn_ItemRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CdnEndpointsWithCdn_ItemRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// CdnEndpointsWithCdn_ItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CdnEndpointsWithCdn_ItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// CdnEndpointsWithCdn_ItemRequestBuilderPutRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CdnEndpointsWithCdn_ItemRequestBuilderPutRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// Cache the cache property
// returns a *CdnEndpointsItemCacheRequestBuilder when successful
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) Cache()(*CdnEndpointsItemCacheRequestBuilder) {
    return NewCdnEndpointsItemCacheRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewCdnEndpointsWithCdn_ItemRequestBuilderInternal instantiates a new CdnEndpointsWithCdn_ItemRequestBuilder and sets the default values.
func NewCdnEndpointsWithCdn_ItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CdnEndpointsWithCdn_ItemRequestBuilder) {
    m := &CdnEndpointsWithCdn_ItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/cdn/endpoints/{cdn_id}", pathParameters),
    }
    return m
}
// NewCdnEndpointsWithCdn_ItemRequestBuilder instantiates a new CdnEndpointsWithCdn_ItemRequestBuilder and sets the default values.
func NewCdnEndpointsWithCdn_ItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CdnEndpointsWithCdn_ItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCdnEndpointsWithCdn_ItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete to delete a specific CDN endpoint, send a DELETE request to`/v2/cdn/endpoints/$ENDPOINT_ID`.A status of 204 will be given. This indicates that the request was processedsuccessfully, but that no response body is needed.
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderDeleteRequestConfiguration)(error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// Get to show information about an existing CDN endpoint, send a GET request to `/v2/cdn/endpoints/$ENDPOINT_ID`.
// Deprecated: This method is obsolete. Use GetAsWithCdn_GetResponse instead.
// returns a CdnEndpointsItemWithCdn_Responseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) Get(ctx context.Context, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderGetRequestConfiguration)(CdnEndpointsItemWithCdn_Responseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateCdnEndpointsItemWithCdn_ResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(CdnEndpointsItemWithCdn_Responseable), nil
}
// GetAsWithCdn_GetResponse to show information about an existing CDN endpoint, send a GET request to `/v2/cdn/endpoints/$ENDPOINT_ID`.
// returns a CdnEndpointsItemWithCdn_GetResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) GetAsWithCdn_GetResponse(ctx context.Context, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderGetRequestConfiguration)(CdnEndpointsItemWithCdn_GetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateCdnEndpointsItemWithCdn_GetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(CdnEndpointsItemWithCdn_GetResponseable), nil
}
// Put to update the TTL, certificate ID, or the FQDN of the custom subdomain foran existing CDN endpoint, send a PUT request to`/v2/cdn/endpoints/$ENDPOINT_ID`.
// Deprecated: This method is obsolete. Use PutAsWithCdn_PutResponse instead.
// returns a CdnEndpointsItemWithCdn_Responseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) Put(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Update_endpointable, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderPutRequestConfiguration)(CdnEndpointsItemWithCdn_Responseable, error) {
    requestInfo, err := m.ToPutRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateCdnEndpointsItemWithCdn_ResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(CdnEndpointsItemWithCdn_Responseable), nil
}
// PutAsWithCdn_PutResponse to update the TTL, certificate ID, or the FQDN of the custom subdomain foran existing CDN endpoint, send a PUT request to`/v2/cdn/endpoints/$ENDPOINT_ID`.
// returns a CdnEndpointsItemWithCdn_PutResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) PutAsWithCdn_PutResponse(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Update_endpointable, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderPutRequestConfiguration)(CdnEndpointsItemWithCdn_PutResponseable, error) {
    requestInfo, err := m.ToPutRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateCdnEndpointsItemWithCdn_PutResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(CdnEndpointsItemWithCdn_PutResponseable), nil
}
// ToDeleteRequestInformation to delete a specific CDN endpoint, send a DELETE request to`/v2/cdn/endpoints/$ENDPOINT_ID`.A status of 204 will be given. This indicates that the request was processedsuccessfully, but that no response body is needed.
// returns a *RequestInformation when successful
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToGetRequestInformation to show information about an existing CDN endpoint, send a GET request to `/v2/cdn/endpoints/$ENDPOINT_ID`.
// returns a *RequestInformation when successful
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPutRequestInformation to update the TTL, certificate ID, or the FQDN of the custom subdomain foran existing CDN endpoint, send a PUT request to`/v2/cdn/endpoints/$ENDPOINT_ID`.
// returns a *RequestInformation when successful
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) ToPutRequestInformation(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Update_endpointable, requestConfiguration *CdnEndpointsWithCdn_ItemRequestBuilderPutRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PUT, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CdnEndpointsWithCdn_ItemRequestBuilder when successful
func (m *CdnEndpointsWithCdn_ItemRequestBuilder) WithUrl(rawUrl string)(*CdnEndpointsWithCdn_ItemRequestBuilder) {
    return NewCdnEndpointsWithCdn_ItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
