// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

type DatabasesMetricsCredentialsGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The credentials property
    credentials i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_metrics_credentialsable
}
// NewDatabasesMetricsCredentialsGetResponse instantiates a new DatabasesMetricsCredentialsGetResponse and sets the default values.
func NewDatabasesMetricsCredentialsGetResponse()(*DatabasesMetricsCredentialsGetResponse) {
    m := &DatabasesMetricsCredentialsGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDatabasesMetricsCredentialsGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDatabasesMetricsCredentialsGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDatabasesMetricsCredentialsGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DatabasesMetricsCredentialsGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCredentials gets the credentials property value. The credentials property
// returns a Database_metrics_credentialsable when successful
func (m *DatabasesMetricsCredentialsGetResponse) GetCredentials()(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_metrics_credentialsable) {
    return m.credentials
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DatabasesMetricsCredentialsGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["credentials"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateDatabase_metrics_credentialsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCredentials(val.(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_metrics_credentialsable))
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *DatabasesMetricsCredentialsGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("credentials", m.GetCredentials())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DatabasesMetricsCredentialsGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCredentials sets the credentials property value. The credentials property
func (m *DatabasesMetricsCredentialsGetResponse) SetCredentials(value i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_metrics_credentialsable)() {
    m.credentials = value
}
type DatabasesMetricsCredentialsGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCredentials()(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_metrics_credentialsable)
    SetCredentials(value i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_metrics_credentialsable)()
}
