// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

type DatabasesItemWithDatabase_cluster_uuGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The database property
    database i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_cluster_readable
}
// NewDatabasesItemWithDatabase_cluster_uuGetResponse instantiates a new DatabasesItemWithDatabase_cluster_uuGetResponse and sets the default values.
func NewDatabasesItemWithDatabase_cluster_uuGetResponse()(*DatabasesItemWithDatabase_cluster_uuGetResponse) {
    m := &DatabasesItemWithDatabase_cluster_uuGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDatabasesItemWithDatabase_cluster_uuGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDatabasesItemWithDatabase_cluster_uuGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDatabasesItemWithDatabase_cluster_uuGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DatabasesItemWithDatabase_cluster_uuGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDatabase gets the database property value. The database property
// returns a Database_cluster_readable when successful
func (m *DatabasesItemWithDatabase_cluster_uuGetResponse) GetDatabase()(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_cluster_readable) {
    return m.database
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DatabasesItemWithDatabase_cluster_uuGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["database"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateDatabase_cluster_readFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDatabase(val.(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_cluster_readable))
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *DatabasesItemWithDatabase_cluster_uuGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("database", m.GetDatabase())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DatabasesItemWithDatabase_cluster_uuGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDatabase sets the database property value. The database property
func (m *DatabasesItemWithDatabase_cluster_uuGetResponse) SetDatabase(value i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_cluster_readable)() {
    m.database = value
}
type DatabasesItemWithDatabase_cluster_uuGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDatabase()(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_cluster_readable)
    SetDatabase(value i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Database_cluster_readable)()
}
