// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// DropletsBackupsRequestBuilder builds and executes requests for operations under \v2\droplets\backups
type DropletsBackupsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewDropletsBackupsRequestBuilderInternal instantiates a new DropletsBackupsRequestBuilder and sets the default values.
func NewDropletsBackupsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DropletsBackupsRequestBuilder) {
    m := &DropletsBackupsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/droplets/backups", pathParameters),
    }
    return m
}
// NewDropletsBackupsRequestBuilder instantiates a new DropletsBackupsRequestBuilder and sets the default values.
func NewDropletsBackupsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DropletsBackupsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewDropletsBackupsRequestBuilderInternal(urlParams, requestAdapter)
}
// Policies the policies property
// returns a *DropletsBackupsPoliciesRequestBuilder when successful
func (m *DropletsBackupsRequestBuilder) Policies()(*DropletsBackupsPoliciesRequestBuilder) {
    return NewDropletsBackupsPoliciesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Supported_policies the supported_policies property
// returns a *DropletsBackupsSupported_policiesRequestBuilder when successful
func (m *DropletsBackupsRequestBuilder) Supported_policies()(*DropletsBackupsSupported_policiesRequestBuilder) {
    return NewDropletsBackupsSupported_policiesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
