// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

// DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder builds and executes requests for operations under \v2\droplets\{droplet_id}\destroy_with_associated_resources\selective
type DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewDropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilderInternal instantiates a new DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder and sets the default values.
func NewDropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder) {
    m := &DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/droplets/{droplet_id}/destroy_with_associated_resources/selective", pathParameters),
    }
    return m
}
// NewDropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder instantiates a new DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder and sets the default values.
func NewDropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewDropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete to destroy a Droplet along with a sub-set of its associated resources, send aDELETE request to the `/v2/droplets/$DROPLET_ID/destroy_with_associated_resources/selective`endpoint. The JSON body of the request should include `reserved_ips`, `snapshots`, `volumes`,or `volume_snapshots` keys each set to an array of IDs for the associatedresources to be destroyed. The IDs can be found by querying the Droplet'sassociated resources. Any associated resource not included in the requestwill remain and continue to accrue changes on your account.A successful response will include a 202 response code and no content. Usethe status endpoint to check on the success or failure of the destruction ofthe individual resources.
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder) Delete(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Selective_destroy_associated_resourceable, requestConfiguration *DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilderDeleteRequestConfiguration)(error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// ToDeleteRequestInformation to destroy a Droplet along with a sub-set of its associated resources, send aDELETE request to the `/v2/droplets/$DROPLET_ID/destroy_with_associated_resources/selective`endpoint. The JSON body of the request should include `reserved_ips`, `snapshots`, `volumes`,or `volume_snapshots` keys each set to an array of IDs for the associatedresources to be destroyed. The IDs can be found by querying the Droplet'sassociated resources. Any associated resource not included in the requestwill remain and continue to accrue changes on your account.A successful response will include a 202 response code and no content. Usethe status endpoint to check on the success or failure of the destruction ofthe individual resources.
// returns a *RequestInformation when successful
func (m *DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder) ToDeleteRequestInformation(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Selective_destroy_associated_resourceable, requestConfiguration *DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder when successful
func (m *DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder) WithUrl(rawUrl string)(*DropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder) {
    return NewDropletsItemDestroy_with_associated_resourcesSelectiveRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
