// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use KubernetesClustersItemStatus_messagesGetResponseable instead.
type KubernetesClustersItemStatus_messagesResponse struct {
    KubernetesClustersItemStatus_messagesGetResponse
}
// NewKubernetesClustersItemStatus_messagesResponse instantiates a new KubernetesClustersItemStatus_messagesResponse and sets the default values.
func NewKubernetesClustersItemStatus_messagesResponse()(*KubernetesClustersItemStatus_messagesResponse) {
    m := &KubernetesClustersItemStatus_messagesResponse{
        KubernetesClustersItemStatus_messagesGetResponse: *NewKubernetesClustersItemStatus_messagesGetResponse(),
    }
    return m
}
// CreateKubernetesClustersItemStatus_messagesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateKubernetesClustersItemStatus_messagesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewKubernetesClustersItemStatus_messagesResponse(), nil
}
// Deprecated: This class is obsolete. Use KubernetesClustersItemStatus_messagesGetResponseable instead.
type KubernetesClustersItemStatus_messagesResponseable interface {
    KubernetesClustersItemStatus_messagesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
