// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RegistriesOptionsGetResponse_options struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The available_regions property
    available_regions []string
    // The subscription_tiers property
    subscription_tiers []RegistriesOptionsGetResponse_options_subscription_tiersable
}
// NewRegistriesOptionsGetResponse_options instantiates a new RegistriesOptionsGetResponse_options and sets the default values.
func NewRegistriesOptionsGetResponse_options()(*RegistriesOptionsGetResponse_options) {
    m := &RegistriesOptionsGetResponse_options{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRegistriesOptionsGetResponse_optionsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRegistriesOptionsGetResponse_optionsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRegistriesOptionsGetResponse_options(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RegistriesOptionsGetResponse_options) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAvailableRegions gets the available_regions property value. The available_regions property
// returns a []string when successful
func (m *RegistriesOptionsGetResponse_options) GetAvailableRegions()([]string) {
    return m.available_regions
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RegistriesOptionsGetResponse_options) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["available_regions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetAvailableRegions(res)
        }
        return nil
    }
    res["subscription_tiers"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateRegistriesOptionsGetResponse_options_subscription_tiersFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]RegistriesOptionsGetResponse_options_subscription_tiersable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(RegistriesOptionsGetResponse_options_subscription_tiersable)
                }
            }
            m.SetSubscriptionTiers(res)
        }
        return nil
    }
    return res
}
// GetSubscriptionTiers gets the subscription_tiers property value. The subscription_tiers property
// returns a []RegistriesOptionsGetResponse_options_subscription_tiersable when successful
func (m *RegistriesOptionsGetResponse_options) GetSubscriptionTiers()([]RegistriesOptionsGetResponse_options_subscription_tiersable) {
    return m.subscription_tiers
}
// Serialize serializes information the current object
func (m *RegistriesOptionsGetResponse_options) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAvailableRegions() != nil {
        err := writer.WriteCollectionOfStringValues("available_regions", m.GetAvailableRegions())
        if err != nil {
            return err
        }
    }
    if m.GetSubscriptionTiers() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSubscriptionTiers()))
        for i, v := range m.GetSubscriptionTiers() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("subscription_tiers", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RegistriesOptionsGetResponse_options) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAvailableRegions sets the available_regions property value. The available_regions property
func (m *RegistriesOptionsGetResponse_options) SetAvailableRegions(value []string)() {
    m.available_regions = value
}
// SetSubscriptionTiers sets the subscription_tiers property value. The subscription_tiers property
func (m *RegistriesOptionsGetResponse_options) SetSubscriptionTiers(value []RegistriesOptionsGetResponse_options_subscription_tiersable)() {
    m.subscription_tiers = value
}
type RegistriesOptionsGetResponse_optionsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAvailableRegions()([]string)
    GetSubscriptionTiers()([]RegistriesOptionsGetResponse_options_subscription_tiersable)
    SetAvailableRegions(value []string)()
    SetSubscriptionTiers(value []RegistriesOptionsGetResponse_options_subscription_tiersable)()
}
