// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

// RegistryRequestBuilder builds and executes requests for operations under \v2\registry
type RegistryRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// RegistryRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type RegistryRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// RegistryRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type RegistryRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// RegistryRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type RegistryRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// ByRegistry_name gets an item from the github.com/harshmaru7/godo-kiota/client.v2.registry.item collection
// returns a *RegistryWithRegistry_nameItemRequestBuilder when successful
func (m *RegistryRequestBuilder) ByRegistry_name(registry_name string)(*RegistryWithRegistry_nameItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if registry_name != "" {
        urlTplParams["registry_name"] = registry_name
    }
    return NewRegistryWithRegistry_nameItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewRegistryRequestBuilderInternal instantiates a new RegistryRequestBuilder and sets the default values.
func NewRegistryRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RegistryRequestBuilder) {
    m := &RegistryRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/registry", pathParameters),
    }
    return m
}
// NewRegistryRequestBuilder instantiates a new RegistryRequestBuilder and sets the default values.
func NewRegistryRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RegistryRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewRegistryRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To delete your container registry, destroying all container imagedata stored in it, send a DELETE request to `/v2/registry`.This operation is not compatible with multiple registries in a DO account. You should use `/v2/registries/{registry_name}` instead.
// Deprecated: 
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 412 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *RegistryRequestBuilder) Delete(ctx context.Context, requestConfiguration *RegistryRequestBuilderDeleteRequestConfiguration)(error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "412": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// DockerCredentials the dockerCredentials property
// returns a *RegistryDockerCredentialsRequestBuilder when successful
func (m *RegistryRequestBuilder) DockerCredentials()(*RegistryDockerCredentialsRequestBuilder) {
    return NewRegistryDockerCredentialsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Get **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To get information about your container registry, send a GETrequest to `/v2/registry`.This operation is not compatible with multiple registries in a DO account. You should use `/v2/registries/{registry_name}` instead.
// Deprecated: This method is obsolete. Use GetAsRegistryGetResponse instead.
// returns a RegistryResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 412 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *RegistryRequestBuilder) Get(ctx context.Context, requestConfiguration *RegistryRequestBuilderGetRequestConfiguration)(RegistryResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "412": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateRegistryResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(RegistryResponseable), nil
}
// GetAsRegistryGetResponse **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To get information about your container registry, send a GETrequest to `/v2/registry`.This operation is not compatible with multiple registries in a DO account. You should use `/v2/registries/{registry_name}` instead.
// Deprecated: 
// returns a RegistryGetResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 412 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *RegistryRequestBuilder) GetAsRegistryGetResponse(ctx context.Context, requestConfiguration *RegistryRequestBuilderGetRequestConfiguration)(RegistryGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "412": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateRegistryGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(RegistryGetResponseable), nil
}
// OptionsPath the optionsPath property
// returns a *RegistryOptionsRequestBuilder when successful
func (m *RegistryRequestBuilder) OptionsPath()(*RegistryOptionsRequestBuilder) {
    return NewRegistryOptionsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Post **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To create your container registry, send a POST request to `/v2/registry`.The `name` becomes part of the URL for images stored in the registry. Forexample, if your registry is called `example`, an image in it will have theURL `registry.digitalocean.com/example/image:tag`.
// Deprecated: This method is obsolete. Use PostAsRegistryPostResponse instead.
// returns a RegistryResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *RegistryRequestBuilder) Post(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Registry_createable, requestConfiguration *RegistryRequestBuilderPostRequestConfiguration)(RegistryResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateRegistryResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(RegistryResponseable), nil
}
// PostAsRegistryPostResponse **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To create your container registry, send a POST request to `/v2/registry`.The `name` becomes part of the URL for images stored in the registry. Forexample, if your registry is called `example`, an image in it will have theURL `registry.digitalocean.com/example/image:tag`.
// Deprecated: 
// returns a RegistryPostResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *RegistryRequestBuilder) PostAsRegistryPostResponse(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Registry_createable, requestConfiguration *RegistryRequestBuilderPostRequestConfiguration)(RegistryPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateRegistryPostResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(RegistryPostResponseable), nil
}
// Subscription the subscription property
// returns a *RegistrySubscriptionRequestBuilder when successful
func (m *RegistryRequestBuilder) Subscription()(*RegistrySubscriptionRequestBuilder) {
    return NewRegistrySubscriptionRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToDeleteRequestInformation **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To delete your container registry, destroying all container imagedata stored in it, send a DELETE request to `/v2/registry`.This operation is not compatible with multiple registries in a DO account. You should use `/v2/registries/{registry_name}` instead.
// Deprecated: 
// returns a *RequestInformation when successful
func (m *RegistryRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *RegistryRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToGetRequestInformation **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To get information about your container registry, send a GETrequest to `/v2/registry`.This operation is not compatible with multiple registries in a DO account. You should use `/v2/registries/{registry_name}` instead.
// Deprecated: 
// returns a *RequestInformation when successful
func (m *RegistryRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *RegistryRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPostRequestInformation **Note: This endpoint is deprecated. Please use the `/v2/registries` endpoint instead.**To create your container registry, send a POST request to `/v2/registry`.The `name` becomes part of the URL for images stored in the registry. Forexample, if your registry is called `example`, an image in it will have theURL `registry.digitalocean.com/example/image:tag`.
// Deprecated: 
// returns a *RequestInformation when successful
func (m *RegistryRequestBuilder) ToPostRequestInformation(ctx context.Context, body i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Registry_createable, requestConfiguration *RegistryRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// ValidateName the validateName property
// returns a *RegistryValidateNameRequestBuilder when successful
func (m *RegistryRequestBuilder) ValidateName()(*RegistryValidateNameRequestBuilder) {
    return NewRegistryValidateNameRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated: 
// returns a *RegistryRequestBuilder when successful
func (m *RegistryRequestBuilder) WithUrl(rawUrl string)(*RegistryRequestBuilder) {
    return NewRegistryRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
