// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

// RegistriesItemRepositoriesItemTagsRequestBuilder builds and executes requests for operations under \v2\registries\{registry_name}\repositories\{repository_name}\tags
type RegistriesItemRepositoriesItemTagsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// RegistriesItemRepositoriesItemTagsRequestBuilderGetQueryParameters to list all tags in one of your container registry's repository, send a GETrequest to `/v2/registries/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.Note that if your repository name contains `/` characters, it must beURL-encoded in the request URL. For example, to list tags for`registry.digitalocean.com/example/my/repo`, the path would be`/v2/registry/example/repositories/my%2Frepo/tags`. It is similar to GET `/v2/registry/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.
type RegistriesItemRepositoriesItemTagsRequestBuilderGetQueryParameters struct {
    // Which 'page' of paginated results to return.
    Page *int32 `uriparametername:"page"`
    // Number of items returned per page
    Per_page *int32 `uriparametername:"per_page"`
}
// RegistriesItemRepositoriesItemTagsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type RegistriesItemRepositoriesItemTagsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *RegistriesItemRepositoriesItemTagsRequestBuilderGetQueryParameters
}
// ByRepository_tag gets an item from the github.com/harshmaru7/godo-kiota/client.v2.registries.item.repositories.item.tags.item collection
// returns a *RegistriesItemRepositoriesItemTagsWithRepository_tagItemRequestBuilder when successful
func (m *RegistriesItemRepositoriesItemTagsRequestBuilder) ByRepository_tag(repository_tag string)(*RegistriesItemRepositoriesItemTagsWithRepository_tagItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if repository_tag != "" {
        urlTplParams["repository_tag"] = repository_tag
    }
    return NewRegistriesItemRepositoriesItemTagsWithRepository_tagItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewRegistriesItemRepositoriesItemTagsRequestBuilderInternal instantiates a new RegistriesItemRepositoriesItemTagsRequestBuilder and sets the default values.
func NewRegistriesItemRepositoriesItemTagsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RegistriesItemRepositoriesItemTagsRequestBuilder) {
    m := &RegistriesItemRepositoriesItemTagsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/registries/{registry_name}/repositories/{repository_name}/tags{?page*,per_page*}", pathParameters),
    }
    return m
}
// NewRegistriesItemRepositoriesItemTagsRequestBuilder instantiates a new RegistriesItemRepositoriesItemTagsRequestBuilder and sets the default values.
func NewRegistriesItemRepositoriesItemTagsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RegistriesItemRepositoriesItemTagsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewRegistriesItemRepositoriesItemTagsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get to list all tags in one of your container registry's repository, send a GETrequest to `/v2/registries/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.Note that if your repository name contains `/` characters, it must beURL-encoded in the request URL. For example, to list tags for`registry.digitalocean.com/example/my/repo`, the path would be`/v2/registry/example/repositories/my%2Frepo/tags`. It is similar to GET `/v2/registry/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.
// Deprecated: This method is obsolete. Use GetAsTagsGetResponse instead.
// returns a RegistriesItemRepositoriesItemTagsResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *RegistriesItemRepositoriesItemTagsRequestBuilder) Get(ctx context.Context, requestConfiguration *RegistriesItemRepositoriesItemTagsRequestBuilderGetRequestConfiguration)(RegistriesItemRepositoriesItemTagsResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateRegistriesItemRepositoriesItemTagsResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(RegistriesItemRepositoriesItemTagsResponseable), nil
}
// GetAsTagsGetResponse to list all tags in one of your container registry's repository, send a GETrequest to `/v2/registries/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.Note that if your repository name contains `/` characters, it must beURL-encoded in the request URL. For example, to list tags for`registry.digitalocean.com/example/my/repo`, the path would be`/v2/registry/example/repositories/my%2Frepo/tags`. It is similar to GET `/v2/registry/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.
// returns a RegistriesItemRepositoriesItemTagsGetResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *RegistriesItemRepositoriesItemTagsRequestBuilder) GetAsTagsGetResponse(ctx context.Context, requestConfiguration *RegistriesItemRepositoriesItemTagsRequestBuilderGetRequestConfiguration)(RegistriesItemRepositoriesItemTagsGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateRegistriesItemRepositoriesItemTagsGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(RegistriesItemRepositoriesItemTagsGetResponseable), nil
}
// ToGetRequestInformation to list all tags in one of your container registry's repository, send a GETrequest to `/v2/registries/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.Note that if your repository name contains `/` characters, it must beURL-encoded in the request URL. For example, to list tags for`registry.digitalocean.com/example/my/repo`, the path would be`/v2/registry/example/repositories/my%2Frepo/tags`. It is similar to GET `/v2/registry/$REGISTRY_NAME/repositories/$REPOSITORY_NAME/tags`.
// returns a *RequestInformation when successful
func (m *RegistriesItemRepositoriesItemTagsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *RegistriesItemRepositoriesItemTagsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *RegistriesItemRepositoriesItemTagsRequestBuilder when successful
func (m *RegistriesItemRepositoriesItemTagsRequestBuilder) WithUrl(rawUrl string)(*RegistriesItemRepositoriesItemTagsRequestBuilder) {
    return NewRegistriesItemRepositoriesItemTagsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
