// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

// SecurityScansItemFindingsItemAffected_resourcesRequestBuilder builds and executes requests for operations under \v2\security\scans\{scan_id}\findings\{finding_uuid}\affected_resources
type SecurityScansItemFindingsItemAffected_resourcesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetQueryParameters to get affected resources for a scan finding, send a GET request to `/v2/security/scans/{scan_id}/findings/{finding_uuid}/affected_resources`.
type SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetQueryParameters struct {
    // Which 'page' of paginated results to return.
    Page *int32 `uriparametername:"page"`
    // Number of items returned per page
    Per_page *int32 `uriparametername:"per_page"`
}
// SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetQueryParameters
}
// NewSecurityScansItemFindingsItemAffected_resourcesRequestBuilderInternal instantiates a new SecurityScansItemFindingsItemAffected_resourcesRequestBuilder and sets the default values.
func NewSecurityScansItemFindingsItemAffected_resourcesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SecurityScansItemFindingsItemAffected_resourcesRequestBuilder) {
    m := &SecurityScansItemFindingsItemAffected_resourcesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/security/scans/{scan_id}/findings/{finding_uuid}/affected_resources{?page*,per_page*}", pathParameters),
    }
    return m
}
// NewSecurityScansItemFindingsItemAffected_resourcesRequestBuilder instantiates a new SecurityScansItemFindingsItemAffected_resourcesRequestBuilder and sets the default values.
func NewSecurityScansItemFindingsItemAffected_resourcesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SecurityScansItemFindingsItemAffected_resourcesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSecurityScansItemFindingsItemAffected_resourcesRequestBuilderInternal(urlParams, requestAdapter)
}
// Get to get affected resources for a scan finding, send a GET request to `/v2/security/scans/{scan_id}/findings/{finding_uuid}/affected_resources`.
// Deprecated: This method is obsolete. Use GetAsAffected_resourcesGetResponse instead.
// returns a SecurityScansItemFindingsItemAffected_resourcesResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *SecurityScansItemFindingsItemAffected_resourcesRequestBuilder) Get(ctx context.Context, requestConfiguration *SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetRequestConfiguration)(SecurityScansItemFindingsItemAffected_resourcesResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateSecurityScansItemFindingsItemAffected_resourcesResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(SecurityScansItemFindingsItemAffected_resourcesResponseable), nil
}
// GetAsAffected_resourcesGetResponse to get affected resources for a scan finding, send a GET request to `/v2/security/scans/{scan_id}/findings/{finding_uuid}/affected_resources`.
// returns a SecurityScansItemFindingsItemAffected_resourcesGetResponseable when successful
// returns a Error error when the service returns a 401 status code
// returns a Error error when the service returns a 404 status code
// returns a Error error when the service returns a 429 status code
// returns a Error error when the service returns a 500 status code
// returns a Error error when the service returns a 4XX or 5XX status code
func (m *SecurityScansItemFindingsItemAffected_resourcesRequestBuilder) GetAsAffected_resourcesGetResponse(ctx context.Context, requestConfiguration *SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetRequestConfiguration)(SecurityScansItemFindingsItemAffected_resourcesGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "401": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "404": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "429": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "500": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
        "XXX": i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateSecurityScansItemFindingsItemAffected_resourcesGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(SecurityScansItemFindingsItemAffected_resourcesGetResponseable), nil
}
// ToGetRequestInformation to get affected resources for a scan finding, send a GET request to `/v2/security/scans/{scan_id}/findings/{finding_uuid}/affected_resources`.
// returns a *RequestInformation when successful
func (m *SecurityScansItemFindingsItemAffected_resourcesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *SecurityScansItemFindingsItemAffected_resourcesRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SecurityScansItemFindingsItemAffected_resourcesRequestBuilder when successful
func (m *SecurityScansItemFindingsItemAffected_resourcesRequestBuilder) WithUrl(rawUrl string)(*SecurityScansItemFindingsItemAffected_resourcesRequestBuilder) {
    return NewSecurityScansItemFindingsItemAffected_resourcesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
