// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76 "github.com/harshmaru7/godo-kiota/client/models"
)

type VpcsItemPeeringsItemWithVpc_peering_PatchResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The peering property
    peering i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Vpc_peeringable
}
// NewVpcsItemPeeringsItemWithVpc_peering_PatchResponse instantiates a new VpcsItemPeeringsItemWithVpc_peering_PatchResponse and sets the default values.
func NewVpcsItemPeeringsItemWithVpc_peering_PatchResponse()(*VpcsItemPeeringsItemWithVpc_peering_PatchResponse) {
    m := &VpcsItemPeeringsItemWithVpc_peering_PatchResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateVpcsItemPeeringsItemWithVpc_peering_PatchResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVpcsItemPeeringsItemWithVpc_peering_PatchResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVpcsItemPeeringsItemWithVpc_peering_PatchResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *VpcsItemPeeringsItemWithVpc_peering_PatchResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *VpcsItemPeeringsItemWithVpc_peering_PatchResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["peering"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.CreateVpc_peeringFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPeering(val.(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Vpc_peeringable))
        }
        return nil
    }
    return res
}
// GetPeering gets the peering property value. The peering property
// returns a Vpc_peeringable when successful
func (m *VpcsItemPeeringsItemWithVpc_peering_PatchResponse) GetPeering()(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Vpc_peeringable) {
    return m.peering
}
// Serialize serializes information the current object
func (m *VpcsItemPeeringsItemWithVpc_peering_PatchResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("peering", m.GetPeering())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *VpcsItemPeeringsItemWithVpc_peering_PatchResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetPeering sets the peering property value. The peering property
func (m *VpcsItemPeeringsItemWithVpc_peering_PatchResponse) SetPeering(value i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Vpc_peeringable)() {
    m.peering = value
}
type VpcsItemPeeringsItemWithVpc_peering_PatchResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPeering()(i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Vpc_peeringable)
    SetPeering(value i3e0d1c568aeb4f96d88b3bf865e0f613ed1556100c1ffe0f3a0a032aa9561f76.Vpc_peeringable)()
}
