// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Addons_dimension_volume_with_price struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Unique identifier for the addon.
    id *int32
    // The minimum volume for the volume pricing tier.
    low_volume *int32
    // The maximum volume for the volume pricing tier.
    max_volume *int32
    // The price per unit for the volume tier in US dollars.
    price_per_unit *string
}
// NewAddons_dimension_volume_with_price instantiates a new Addons_dimension_volume_with_price and sets the default values.
func NewAddons_dimension_volume_with_price()(*Addons_dimension_volume_with_price) {
    m := &Addons_dimension_volume_with_price{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAddons_dimension_volume_with_priceFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAddons_dimension_volume_with_priceFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAddons_dimension_volume_with_price(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Addons_dimension_volume_with_price) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Addons_dimension_volume_with_price) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["low_volume"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLowVolume(val)
        }
        return nil
    }
    res["max_volume"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMaxVolume(val)
        }
        return nil
    }
    res["price_per_unit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPricePerUnit(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. Unique identifier for the addon.
// returns a *int32 when successful
func (m *Addons_dimension_volume_with_price) GetId()(*int32) {
    return m.id
}
// GetLowVolume gets the low_volume property value. The minimum volume for the volume pricing tier.
// returns a *int32 when successful
func (m *Addons_dimension_volume_with_price) GetLowVolume()(*int32) {
    return m.low_volume
}
// GetMaxVolume gets the max_volume property value. The maximum volume for the volume pricing tier.
// returns a *int32 when successful
func (m *Addons_dimension_volume_with_price) GetMaxVolume()(*int32) {
    return m.max_volume
}
// GetPricePerUnit gets the price_per_unit property value. The price per unit for the volume tier in US dollars.
// returns a *string when successful
func (m *Addons_dimension_volume_with_price) GetPricePerUnit()(*string) {
    return m.price_per_unit
}
// Serialize serializes information the current object
func (m *Addons_dimension_volume_with_price) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("low_volume", m.GetLowVolume())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("max_volume", m.GetMaxVolume())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("price_per_unit", m.GetPricePerUnit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Addons_dimension_volume_with_price) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetId sets the id property value. Unique identifier for the addon.
func (m *Addons_dimension_volume_with_price) SetId(value *int32)() {
    m.id = value
}
// SetLowVolume sets the low_volume property value. The minimum volume for the volume pricing tier.
func (m *Addons_dimension_volume_with_price) SetLowVolume(value *int32)() {
    m.low_volume = value
}
// SetMaxVolume sets the max_volume property value. The maximum volume for the volume pricing tier.
func (m *Addons_dimension_volume_with_price) SetMaxVolume(value *int32)() {
    m.max_volume = value
}
// SetPricePerUnit sets the price_per_unit property value. The price per unit for the volume tier in US dollars.
func (m *Addons_dimension_volume_with_price) SetPricePerUnit(value *string)() {
    m.price_per_unit = value
}
type Addons_dimension_volume_with_priceable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetId()(*int32)
    GetLowVolume()(*int32)
    GetMaxVolume()(*int32)
    GetPricePerUnit()(*string)
    SetId(value *int32)()
    SetLowVolume(value *int32)()
    SetMaxVolume(value *int32)()
    SetPricePerUnit(value *string)()
}
