// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Addons_plan struct {
    // Indicates if the plan is currently active.
    active *bool
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // ID of the app associated with this plan.
    app_id *int32
    // Indicates if the plan is available for selection.
    available *bool
    // Indicates if this plan is the default option for the app.
    by_default *bool
    // Timestamp when the plan was created.
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Description of an app plan.
    description *string
    // List of dimensions associated with the plan, each with its own pricing.
    dimensions []Addons_dimension_with_priceable
    // Display name for a given plan.
    display_name *string
    // List of features included in the plan.
    features []Addons_featureable
    // ID of a given plan.
    id *int32
    // Price of a month's usage of the plan in US dollars.
    price_per_month *int32
    // Slug identifier for the plan.
    slug *string
    // Current state of the plan.
    state *Addons_plan_state
    // Timestamp when the plan was last updated.
    updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Unique identifier for the plan.
    uuid *string
}
// NewAddons_plan instantiates a new Addons_plan and sets the default values.
func NewAddons_plan()(*Addons_plan) {
    m := &Addons_plan{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAddons_planFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAddons_planFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAddons_plan(), nil
}
// GetActive gets the active property value. Indicates if the plan is currently active.
// returns a *bool when successful
func (m *Addons_plan) GetActive()(*bool) {
    return m.active
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Addons_plan) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAppId gets the app_id property value. ID of the app associated with this plan.
// returns a *int32 when successful
func (m *Addons_plan) GetAppId()(*int32) {
    return m.app_id
}
// GetAvailable gets the available property value. Indicates if the plan is available for selection.
// returns a *bool when successful
func (m *Addons_plan) GetAvailable()(*bool) {
    return m.available
}
// GetByDefault gets the by_default property value. Indicates if this plan is the default option for the app.
// returns a *bool when successful
func (m *Addons_plan) GetByDefault()(*bool) {
    return m.by_default
}
// GetCreatedAt gets the created_at property value. Timestamp when the plan was created.
// returns a *Time when successful
func (m *Addons_plan) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetDescription gets the description property value. Description of an app plan.
// returns a *string when successful
func (m *Addons_plan) GetDescription()(*string) {
    return m.description
}
// GetDimensions gets the dimensions property value. List of dimensions associated with the plan, each with its own pricing.
// returns a []Addons_dimension_with_priceable when successful
func (m *Addons_plan) GetDimensions()([]Addons_dimension_with_priceable) {
    return m.dimensions
}
// GetDisplayName gets the display_name property value. Display name for a given plan.
// returns a *string when successful
func (m *Addons_plan) GetDisplayName()(*string) {
    return m.display_name
}
// GetFeatures gets the features property value. List of features included in the plan.
// returns a []Addons_featureable when successful
func (m *Addons_plan) GetFeatures()([]Addons_featureable) {
    return m.features
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Addons_plan) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["active"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActive(val)
        }
        return nil
    }
    res["app_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAppId(val)
        }
        return nil
    }
    res["available"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAvailable(val)
        }
        return nil
    }
    res["by_default"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetByDefault(val)
        }
        return nil
    }
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["dimensions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAddons_dimension_with_priceFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Addons_dimension_with_priceable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Addons_dimension_with_priceable)
                }
            }
            m.SetDimensions(res)
        }
        return nil
    }
    res["display_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDisplayName(val)
        }
        return nil
    }
    res["features"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAddons_featureFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Addons_featureable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Addons_featureable)
                }
            }
            m.SetFeatures(res)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["price_per_month"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPricePerMonth(val)
        }
        return nil
    }
    res["slug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSlug(val)
        }
        return nil
    }
    res["state"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseAddons_plan_state)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetState(val.(*Addons_plan_state))
        }
        return nil
    }
    res["updated_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    res["uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUuid(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. ID of a given plan.
// returns a *int32 when successful
func (m *Addons_plan) GetId()(*int32) {
    return m.id
}
// GetPricePerMonth gets the price_per_month property value. Price of a month's usage of the plan in US dollars.
// returns a *int32 when successful
func (m *Addons_plan) GetPricePerMonth()(*int32) {
    return m.price_per_month
}
// GetSlug gets the slug property value. Slug identifier for the plan.
// returns a *string when successful
func (m *Addons_plan) GetSlug()(*string) {
    return m.slug
}
// GetState gets the state property value. Current state of the plan.
// returns a *Addons_plan_state when successful
func (m *Addons_plan) GetState()(*Addons_plan_state) {
    return m.state
}
// GetUpdatedAt gets the updated_at property value. Timestamp when the plan was last updated.
// returns a *Time when successful
func (m *Addons_plan) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updated_at
}
// GetUuid gets the uuid property value. Unique identifier for the plan.
// returns a *string when successful
func (m *Addons_plan) GetUuid()(*string) {
    return m.uuid
}
// Serialize serializes information the current object
func (m *Addons_plan) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("active", m.GetActive())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("app_id", m.GetAppId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("available", m.GetAvailable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("by_default", m.GetByDefault())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("created_at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    if m.GetDimensions() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetDimensions()))
        for i, v := range m.GetDimensions() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("dimensions", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("display_name", m.GetDisplayName())
        if err != nil {
            return err
        }
    }
    if m.GetFeatures() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetFeatures()))
        for i, v := range m.GetFeatures() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("features", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("price_per_month", m.GetPricePerMonth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("slug", m.GetSlug())
        if err != nil {
            return err
        }
    }
    if m.GetState() != nil {
        cast := (*m.GetState()).String()
        err := writer.WriteStringValue("state", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("updated_at", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("uuid", m.GetUuid())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActive sets the active property value. Indicates if the plan is currently active.
func (m *Addons_plan) SetActive(value *bool)() {
    m.active = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Addons_plan) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAppId sets the app_id property value. ID of the app associated with this plan.
func (m *Addons_plan) SetAppId(value *int32)() {
    m.app_id = value
}
// SetAvailable sets the available property value. Indicates if the plan is available for selection.
func (m *Addons_plan) SetAvailable(value *bool)() {
    m.available = value
}
// SetByDefault sets the by_default property value. Indicates if this plan is the default option for the app.
func (m *Addons_plan) SetByDefault(value *bool)() {
    m.by_default = value
}
// SetCreatedAt sets the created_at property value. Timestamp when the plan was created.
func (m *Addons_plan) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetDescription sets the description property value. Description of an app plan.
func (m *Addons_plan) SetDescription(value *string)() {
    m.description = value
}
// SetDimensions sets the dimensions property value. List of dimensions associated with the plan, each with its own pricing.
func (m *Addons_plan) SetDimensions(value []Addons_dimension_with_priceable)() {
    m.dimensions = value
}
// SetDisplayName sets the display_name property value. Display name for a given plan.
func (m *Addons_plan) SetDisplayName(value *string)() {
    m.display_name = value
}
// SetFeatures sets the features property value. List of features included in the plan.
func (m *Addons_plan) SetFeatures(value []Addons_featureable)() {
    m.features = value
}
// SetId sets the id property value. ID of a given plan.
func (m *Addons_plan) SetId(value *int32)() {
    m.id = value
}
// SetPricePerMonth sets the price_per_month property value. Price of a month's usage of the plan in US dollars.
func (m *Addons_plan) SetPricePerMonth(value *int32)() {
    m.price_per_month = value
}
// SetSlug sets the slug property value. Slug identifier for the plan.
func (m *Addons_plan) SetSlug(value *string)() {
    m.slug = value
}
// SetState sets the state property value. Current state of the plan.
func (m *Addons_plan) SetState(value *Addons_plan_state)() {
    m.state = value
}
// SetUpdatedAt sets the updated_at property value. Timestamp when the plan was last updated.
func (m *Addons_plan) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updated_at = value
}
// SetUuid sets the uuid property value. Unique identifier for the plan.
func (m *Addons_plan) SetUuid(value *string)() {
    m.uuid = value
}
type Addons_planable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActive()(*bool)
    GetAppId()(*int32)
    GetAvailable()(*bool)
    GetByDefault()(*bool)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetDescription()(*string)
    GetDimensions()([]Addons_dimension_with_priceable)
    GetDisplayName()(*string)
    GetFeatures()([]Addons_featureable)
    GetId()(*int32)
    GetPricePerMonth()(*int32)
    GetSlug()(*string)
    GetState()(*Addons_plan_state)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetUuid()(*string)
    SetActive(value *bool)()
    SetAppId(value *int32)()
    SetAvailable(value *bool)()
    SetByDefault(value *bool)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetDescription(value *string)()
    SetDimensions(value []Addons_dimension_with_priceable)()
    SetDisplayName(value *string)()
    SetFeatures(value []Addons_featureable)()
    SetId(value *int32)()
    SetPricePerMonth(value *int32)()
    SetSlug(value *string)()
    SetState(value *Addons_plan_state)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetUuid(value *string)()
}
