// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// - AGENT_TEMPLATE_TYPE_STANDARD: The standard agent template - AGENT_TEMPLATE_TYPE_ONE_CLICK: The one click agent template
type ApiAgentTemplateType int

const (
    AGENT_TEMPLATE_TYPE_STANDARD_APIAGENTTEMPLATETYPE ApiAgentTemplateType = iota
    AGENT_TEMPLATE_TYPE_ONE_CLICK_APIAGENTTEMPLATETYPE
)

func (i ApiAgentTemplateType) String() string {
    return []string{"AGENT_TEMPLATE_TYPE_STANDARD", "AGENT_TEMPLATE_TYPE_ONE_CLICK"}[i]
}
func ParseApiAgentTemplateType(v string) (any, error) {
    result := AGENT_TEMPLATE_TYPE_STANDARD_APIAGENTTEMPLATETYPE
    switch v {
        case "AGENT_TEMPLATE_TYPE_STANDARD":
            result = AGENT_TEMPLATE_TYPE_STANDARD_APIAGENTTEMPLATETYPE
        case "AGENT_TEMPLATE_TYPE_ONE_CLICK":
            result = AGENT_TEMPLATE_TYPE_ONE_CLICK_APIAGENTTEMPLATETYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeApiAgentTemplateType(values []ApiAgentTemplateType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ApiAgentTemplateType) isMultiValue() bool {
    return false
}
