// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ApiLLMSpan lLM span
type ApiLLMSpan struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Common optional fields shared by all span types
    common ApiSpanCommonable
    // The model property
    model *string
    // The num_input_tokens property
    num_input_tokens *int32
    // The num_output_tokens property
    num_output_tokens *int32
    // The temperature property
    temperature *float32
    // The time_to_first_token_ns property
    time_to_first_token_ns *string
    // Tool definitions passed to the model
    tools []ApiLLMSpan_toolsable
    // The total_tokens property
    total_tokens *int32
}
// NewApiLLMSpan instantiates a new ApiLLMSpan and sets the default values.
func NewApiLLMSpan()(*ApiLLMSpan) {
    m := &ApiLLMSpan{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateApiLLMSpanFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateApiLLMSpanFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewApiLLMSpan(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ApiLLMSpan) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCommon gets the common property value. Common optional fields shared by all span types
// returns a ApiSpanCommonable when successful
func (m *ApiLLMSpan) GetCommon()(ApiSpanCommonable) {
    return m.common
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ApiLLMSpan) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["common"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApiSpanCommonFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCommon(val.(ApiSpanCommonable))
        }
        return nil
    }
    res["model"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModel(val)
        }
        return nil
    }
    res["num_input_tokens"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNumInputTokens(val)
        }
        return nil
    }
    res["num_output_tokens"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNumOutputTokens(val)
        }
        return nil
    }
    res["temperature"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTemperature(val)
        }
        return nil
    }
    res["time_to_first_token_ns"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTimeToFirstTokenNs(val)
        }
        return nil
    }
    res["tools"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApiLLMSpan_toolsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ApiLLMSpan_toolsable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ApiLLMSpan_toolsable)
                }
            }
            m.SetTools(res)
        }
        return nil
    }
    res["total_tokens"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalTokens(val)
        }
        return nil
    }
    return res
}
// GetModel gets the model property value. The model property
// returns a *string when successful
func (m *ApiLLMSpan) GetModel()(*string) {
    return m.model
}
// GetNumInputTokens gets the num_input_tokens property value. The num_input_tokens property
// returns a *int32 when successful
func (m *ApiLLMSpan) GetNumInputTokens()(*int32) {
    return m.num_input_tokens
}
// GetNumOutputTokens gets the num_output_tokens property value. The num_output_tokens property
// returns a *int32 when successful
func (m *ApiLLMSpan) GetNumOutputTokens()(*int32) {
    return m.num_output_tokens
}
// GetTemperature gets the temperature property value. The temperature property
// returns a *float32 when successful
func (m *ApiLLMSpan) GetTemperature()(*float32) {
    return m.temperature
}
// GetTimeToFirstTokenNs gets the time_to_first_token_ns property value. The time_to_first_token_ns property
// returns a *string when successful
func (m *ApiLLMSpan) GetTimeToFirstTokenNs()(*string) {
    return m.time_to_first_token_ns
}
// GetTools gets the tools property value. Tool definitions passed to the model
// returns a []ApiLLMSpan_toolsable when successful
func (m *ApiLLMSpan) GetTools()([]ApiLLMSpan_toolsable) {
    return m.tools
}
// GetTotalTokens gets the total_tokens property value. The total_tokens property
// returns a *int32 when successful
func (m *ApiLLMSpan) GetTotalTokens()(*int32) {
    return m.total_tokens
}
// Serialize serializes information the current object
func (m *ApiLLMSpan) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("common", m.GetCommon())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("model", m.GetModel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("num_input_tokens", m.GetNumInputTokens())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("num_output_tokens", m.GetNumOutputTokens())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat32Value("temperature", m.GetTemperature())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("time_to_first_token_ns", m.GetTimeToFirstTokenNs())
        if err != nil {
            return err
        }
    }
    if m.GetTools() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetTools()))
        for i, v := range m.GetTools() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("tools", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("total_tokens", m.GetTotalTokens())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ApiLLMSpan) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCommon sets the common property value. Common optional fields shared by all span types
func (m *ApiLLMSpan) SetCommon(value ApiSpanCommonable)() {
    m.common = value
}
// SetModel sets the model property value. The model property
func (m *ApiLLMSpan) SetModel(value *string)() {
    m.model = value
}
// SetNumInputTokens sets the num_input_tokens property value. The num_input_tokens property
func (m *ApiLLMSpan) SetNumInputTokens(value *int32)() {
    m.num_input_tokens = value
}
// SetNumOutputTokens sets the num_output_tokens property value. The num_output_tokens property
func (m *ApiLLMSpan) SetNumOutputTokens(value *int32)() {
    m.num_output_tokens = value
}
// SetTemperature sets the temperature property value. The temperature property
func (m *ApiLLMSpan) SetTemperature(value *float32)() {
    m.temperature = value
}
// SetTimeToFirstTokenNs sets the time_to_first_token_ns property value. The time_to_first_token_ns property
func (m *ApiLLMSpan) SetTimeToFirstTokenNs(value *string)() {
    m.time_to_first_token_ns = value
}
// SetTools sets the tools property value. Tool definitions passed to the model
func (m *ApiLLMSpan) SetTools(value []ApiLLMSpan_toolsable)() {
    m.tools = value
}
// SetTotalTokens sets the total_tokens property value. The total_tokens property
func (m *ApiLLMSpan) SetTotalTokens(value *int32)() {
    m.total_tokens = value
}
type ApiLLMSpanable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCommon()(ApiSpanCommonable)
    GetModel()(*string)
    GetNumInputTokens()(*int32)
    GetNumOutputTokens()(*int32)
    GetTemperature()(*float32)
    GetTimeToFirstTokenNs()(*string)
    GetTools()([]ApiLLMSpan_toolsable)
    GetTotalTokens()(*int32)
    SetCommon(value ApiSpanCommonable)()
    SetModel(value *string)()
    SetNumInputTokens(value *int32)()
    SetNumOutputTokens(value *int32)()
    SetTemperature(value *float32)()
    SetTimeToFirstTokenNs(value *string)()
    SetTools(value []ApiLLMSpan_toolsable)()
    SetTotalTokens(value *int32)()
}
