// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ApiCreateKnowledgeBaseInputPublic data to create a new knowledge base.
type ApiCreateKnowledgeBaseInputPublic struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Identifier of the DigitalOcean OpenSearch database this knowledge base will use, optional.If not provided, we create a new database for the knowledge base inthe same region as the knowledge base.
    database_id *string
    // Optional data sources to attach at creation. Omit or use an empty list to create the knowledge base without sources, then add sources (with chunking strategy and sizes) using [Add a Data Source to a Knowledge Base](#operation/create_knowledge_base_data_source). When provided, see [Organize Data Sources](https://docs.digitalocean.com/products/gradient-ai-platform/how-to/create-manage-agent-knowledge-bases/#add-data-sources) for best practices.
    datasources []ApiKBDataSourceable
    // Identifier for the [embedding model](https://docs.digitalocean.com/products/genai-platform/details/models/#embedding-models).
    embedding_model_uuid *string
    // Name of the knowledge base.
    name *string
    // Identifier of the DigitalOcean project this knowledge base will belong to.
    project_id *string
    // The datacenter region to deploy the knowledge base in.
    region *string
    // Configuration for cross-encoder reranking during retrieval.
    reranking_config ApiRerankingConfigurationable
    // The size property
    size *ApiOpenSearchPlanSize
    // Tags to organize your knowledge base.
    tags []string
    // The VPC to deploy the knowledge base database in
    vpc_uuid *string
}
// NewApiCreateKnowledgeBaseInputPublic instantiates a new ApiCreateKnowledgeBaseInputPublic and sets the default values.
func NewApiCreateKnowledgeBaseInputPublic()(*ApiCreateKnowledgeBaseInputPublic) {
    m := &ApiCreateKnowledgeBaseInputPublic{
    }
    m.SetAdditionalData(make(map[string]any))
    sizeValue := OPEN_SEARCH_PLAN_SIZE_UNSPECIFIED_APIOPENSEARCHPLANSIZE
    m.SetSize(&sizeValue)
    return m
}
// CreateApiCreateKnowledgeBaseInputPublicFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateApiCreateKnowledgeBaseInputPublicFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewApiCreateKnowledgeBaseInputPublic(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDatabaseId gets the database_id property value. Identifier of the DigitalOcean OpenSearch database this knowledge base will use, optional.If not provided, we create a new database for the knowledge base inthe same region as the knowledge base.
// returns a *string when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetDatabaseId()(*string) {
    return m.database_id
}
// GetDatasources gets the datasources property value. Optional data sources to attach at creation. Omit or use an empty list to create the knowledge base without sources, then add sources (with chunking strategy and sizes) using [Add a Data Source to a Knowledge Base](#operation/create_knowledge_base_data_source). When provided, see [Organize Data Sources](https://docs.digitalocean.com/products/gradient-ai-platform/how-to/create-manage-agent-knowledge-bases/#add-data-sources) for best practices.
// returns a []ApiKBDataSourceable when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetDatasources()([]ApiKBDataSourceable) {
    return m.datasources
}
// GetEmbeddingModelUuid gets the embedding_model_uuid property value. Identifier for the [embedding model](https://docs.digitalocean.com/products/genai-platform/details/models/#embedding-models).
// returns a *string when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetEmbeddingModelUuid()(*string) {
    return m.embedding_model_uuid
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["database_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDatabaseId(val)
        }
        return nil
    }
    res["datasources"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApiKBDataSourceFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ApiKBDataSourceable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ApiKBDataSourceable)
                }
            }
            m.SetDatasources(res)
        }
        return nil
    }
    res["embedding_model_uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmbeddingModelUuid(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["project_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProjectId(val)
        }
        return nil
    }
    res["region"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRegion(val)
        }
        return nil
    }
    res["reranking_config"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApiRerankingConfigurationFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRerankingConfig(val.(ApiRerankingConfigurationable))
        }
        return nil
    }
    res["size"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseApiOpenSearchPlanSize)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSize(val.(*ApiOpenSearchPlanSize))
        }
        return nil
    }
    res["tags"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetTags(res)
        }
        return nil
    }
    res["vpc_uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVpcUuid(val)
        }
        return nil
    }
    return res
}
// GetName gets the name property value. Name of the knowledge base.
// returns a *string when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetName()(*string) {
    return m.name
}
// GetProjectId gets the project_id property value. Identifier of the DigitalOcean project this knowledge base will belong to.
// returns a *string when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetProjectId()(*string) {
    return m.project_id
}
// GetRegion gets the region property value. The datacenter region to deploy the knowledge base in.
// returns a *string when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetRegion()(*string) {
    return m.region
}
// GetRerankingConfig gets the reranking_config property value. Configuration for cross-encoder reranking during retrieval.
// returns a ApiRerankingConfigurationable when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetRerankingConfig()(ApiRerankingConfigurationable) {
    return m.reranking_config
}
// GetSize gets the size property value. The size property
// returns a *ApiOpenSearchPlanSize when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetSize()(*ApiOpenSearchPlanSize) {
    return m.size
}
// GetTags gets the tags property value. Tags to organize your knowledge base.
// returns a []string when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetTags()([]string) {
    return m.tags
}
// GetVpcUuid gets the vpc_uuid property value. The VPC to deploy the knowledge base database in
// returns a *string when successful
func (m *ApiCreateKnowledgeBaseInputPublic) GetVpcUuid()(*string) {
    return m.vpc_uuid
}
// Serialize serializes information the current object
func (m *ApiCreateKnowledgeBaseInputPublic) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("database_id", m.GetDatabaseId())
        if err != nil {
            return err
        }
    }
    if m.GetDatasources() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetDatasources()))
        for i, v := range m.GetDatasources() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("datasources", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("embedding_model_uuid", m.GetEmbeddingModelUuid())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("project_id", m.GetProjectId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("region", m.GetRegion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("reranking_config", m.GetRerankingConfig())
        if err != nil {
            return err
        }
    }
    if m.GetSize() != nil {
        cast := (*m.GetSize()).String()
        err := writer.WriteStringValue("size", &cast)
        if err != nil {
            return err
        }
    }
    if m.GetTags() != nil {
        err := writer.WriteCollectionOfStringValues("tags", m.GetTags())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("vpc_uuid", m.GetVpcUuid())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ApiCreateKnowledgeBaseInputPublic) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDatabaseId sets the database_id property value. Identifier of the DigitalOcean OpenSearch database this knowledge base will use, optional.If not provided, we create a new database for the knowledge base inthe same region as the knowledge base.
func (m *ApiCreateKnowledgeBaseInputPublic) SetDatabaseId(value *string)() {
    m.database_id = value
}
// SetDatasources sets the datasources property value. Optional data sources to attach at creation. Omit or use an empty list to create the knowledge base without sources, then add sources (with chunking strategy and sizes) using [Add a Data Source to a Knowledge Base](#operation/create_knowledge_base_data_source). When provided, see [Organize Data Sources](https://docs.digitalocean.com/products/gradient-ai-platform/how-to/create-manage-agent-knowledge-bases/#add-data-sources) for best practices.
func (m *ApiCreateKnowledgeBaseInputPublic) SetDatasources(value []ApiKBDataSourceable)() {
    m.datasources = value
}
// SetEmbeddingModelUuid sets the embedding_model_uuid property value. Identifier for the [embedding model](https://docs.digitalocean.com/products/genai-platform/details/models/#embedding-models).
func (m *ApiCreateKnowledgeBaseInputPublic) SetEmbeddingModelUuid(value *string)() {
    m.embedding_model_uuid = value
}
// SetName sets the name property value. Name of the knowledge base.
func (m *ApiCreateKnowledgeBaseInputPublic) SetName(value *string)() {
    m.name = value
}
// SetProjectId sets the project_id property value. Identifier of the DigitalOcean project this knowledge base will belong to.
func (m *ApiCreateKnowledgeBaseInputPublic) SetProjectId(value *string)() {
    m.project_id = value
}
// SetRegion sets the region property value. The datacenter region to deploy the knowledge base in.
func (m *ApiCreateKnowledgeBaseInputPublic) SetRegion(value *string)() {
    m.region = value
}
// SetRerankingConfig sets the reranking_config property value. Configuration for cross-encoder reranking during retrieval.
func (m *ApiCreateKnowledgeBaseInputPublic) SetRerankingConfig(value ApiRerankingConfigurationable)() {
    m.reranking_config = value
}
// SetSize sets the size property value. The size property
func (m *ApiCreateKnowledgeBaseInputPublic) SetSize(value *ApiOpenSearchPlanSize)() {
    m.size = value
}
// SetTags sets the tags property value. Tags to organize your knowledge base.
func (m *ApiCreateKnowledgeBaseInputPublic) SetTags(value []string)() {
    m.tags = value
}
// SetVpcUuid sets the vpc_uuid property value. The VPC to deploy the knowledge base database in
func (m *ApiCreateKnowledgeBaseInputPublic) SetVpcUuid(value *string)() {
    m.vpc_uuid = value
}
type ApiCreateKnowledgeBaseInputPublicable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDatabaseId()(*string)
    GetDatasources()([]ApiKBDataSourceable)
    GetEmbeddingModelUuid()(*string)
    GetName()(*string)
    GetProjectId()(*string)
    GetRegion()(*string)
    GetRerankingConfig()(ApiRerankingConfigurationable)
    GetSize()(*ApiOpenSearchPlanSize)
    GetTags()([]string)
    GetVpcUuid()(*string)
    SetDatabaseId(value *string)()
    SetDatasources(value []ApiKBDataSourceable)()
    SetEmbeddingModelUuid(value *string)()
    SetName(value *string)()
    SetProjectId(value *string)()
    SetRegion(value *string)()
    SetRerankingConfig(value ApiRerankingConfigurationable)()
    SetSize(value *ApiOpenSearchPlanSize)()
    SetTags(value []string)()
    SetVpcUuid(value *string)()
}
