// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Options for specifying how URLs found on pages should be handled. - UNKNOWN: Default unknown value - SCOPED: Only include the base URL. - PATH: Crawl the base URL and linked pages within the URL path. - DOMAIN: Crawl the base URL and linked pages within the same domain. - SUBDOMAINS: Crawl the base URL and linked pages for any subdomain. - SITEMAP: Crawl URLs discovered in the sitemap.
type ApiCrawlingOption int

const (
    UNKNOWN_APICRAWLINGOPTION ApiCrawlingOption = iota
    SCOPED_APICRAWLINGOPTION
    PATH_APICRAWLINGOPTION
    DOMAIN_APICRAWLINGOPTION
    SUBDOMAINS_APICRAWLINGOPTION
    SITEMAP_APICRAWLINGOPTION
)

func (i ApiCrawlingOption) String() string {
    return []string{"UNKNOWN", "SCOPED", "PATH", "DOMAIN", "SUBDOMAINS", "SITEMAP"}[i]
}
func ParseApiCrawlingOption(v string) (any, error) {
    result := UNKNOWN_APICRAWLINGOPTION
    switch v {
        case "UNKNOWN":
            result = UNKNOWN_APICRAWLINGOPTION
        case "SCOPED":
            result = SCOPED_APICRAWLINGOPTION
        case "PATH":
            result = PATH_APICRAWLINGOPTION
        case "DOMAIN":
            result = DOMAIN_APICRAWLINGOPTION
        case "SUBDOMAINS":
            result = SUBDOMAINS_APICRAWLINGOPTION
        case "SITEMAP":
            result = SITEMAP_APICRAWLINGOPTION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeApiCrawlingOption(values []ApiCrawlingOption) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ApiCrawlingOption) isMultiValue() bool {
    return false
}
