// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// App an application's configuration and status.
type App struct {
    // The active_deployment property
    active_deployment Apps_deploymentable
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The created_at property
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The dedicated_ips property
    dedicated_ips []Apps_dedicated_egress_ipable
    // The default_ingress property
    default_ingress *string
    // The domains property
    domains []Apps_domainable
    // The id property
    id *string
    // The in_progress_deployment property
    in_progress_deployment Apps_deploymentable
    // The last_deployment_created_at property
    last_deployment_created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The live_domain property
    live_domain *string
    // The live_url property
    live_url *string
    // The live_url_base property
    live_url_base *string
    // The owner_uuid property
    owner_uuid *string
    // The pending_deployment property
    pending_deployment Apps_deploymentable
    // The pinned_deployment property
    pinned_deployment Apps_deploymentable
    // Requires `project:read` scope.
    project_id *string
    // The region property
    region Apps_regionable
    // The desired configuration of an application.
    spec App_specable
    // The tier_slug property
    tier_slug *string
    // The updated_at property
    updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The vpc property
    vpc Apps_vpcable
}
// NewApp instantiates a new App and sets the default values.
func NewApp()(*App) {
    m := &App{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAppFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAppFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewApp(), nil
}
// GetActiveDeployment gets the active_deployment property value. The active_deployment property
// returns a Apps_deploymentable when successful
func (m *App) GetActiveDeployment()(Apps_deploymentable) {
    return m.active_deployment
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *App) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the created_at property value. The created_at property
// returns a *Time when successful
func (m *App) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetDedicatedIps gets the dedicated_ips property value. The dedicated_ips property
// returns a []Apps_dedicated_egress_ipable when successful
func (m *App) GetDedicatedIps()([]Apps_dedicated_egress_ipable) {
    return m.dedicated_ips
}
// GetDefaultIngress gets the default_ingress property value. The default_ingress property
// returns a *string when successful
func (m *App) GetDefaultIngress()(*string) {
    return m.default_ingress
}
// GetDomains gets the domains property value. The domains property
// returns a []Apps_domainable when successful
func (m *App) GetDomains()([]Apps_domainable) {
    return m.domains
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *App) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["active_deployment"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApps_deploymentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActiveDeployment(val.(Apps_deploymentable))
        }
        return nil
    }
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["dedicated_ips"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApps_dedicated_egress_ipFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Apps_dedicated_egress_ipable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Apps_dedicated_egress_ipable)
                }
            }
            m.SetDedicatedIps(res)
        }
        return nil
    }
    res["default_ingress"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDefaultIngress(val)
        }
        return nil
    }
    res["domains"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApps_domainFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Apps_domainable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Apps_domainable)
                }
            }
            m.SetDomains(res)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["in_progress_deployment"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApps_deploymentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInProgressDeployment(val.(Apps_deploymentable))
        }
        return nil
    }
    res["last_deployment_created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastDeploymentCreatedAt(val)
        }
        return nil
    }
    res["live_domain"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLiveDomain(val)
        }
        return nil
    }
    res["live_url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLiveUrl(val)
        }
        return nil
    }
    res["live_url_base"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLiveUrlBase(val)
        }
        return nil
    }
    res["owner_uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOwnerUuid(val)
        }
        return nil
    }
    res["pending_deployment"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApps_deploymentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPendingDeployment(val.(Apps_deploymentable))
        }
        return nil
    }
    res["pinned_deployment"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApps_deploymentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPinnedDeployment(val.(Apps_deploymentable))
        }
        return nil
    }
    res["project_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProjectId(val)
        }
        return nil
    }
    res["region"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApps_regionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRegion(val.(Apps_regionable))
        }
        return nil
    }
    res["spec"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApp_specFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSpec(val.(App_specable))
        }
        return nil
    }
    res["tier_slug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTierSlug(val)
        }
        return nil
    }
    res["updated_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    res["vpc"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateApps_vpcFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVpc(val.(Apps_vpcable))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *App) GetId()(*string) {
    return m.id
}
// GetInProgressDeployment gets the in_progress_deployment property value. The in_progress_deployment property
// returns a Apps_deploymentable when successful
func (m *App) GetInProgressDeployment()(Apps_deploymentable) {
    return m.in_progress_deployment
}
// GetLastDeploymentCreatedAt gets the last_deployment_created_at property value. The last_deployment_created_at property
// returns a *Time when successful
func (m *App) GetLastDeploymentCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.last_deployment_created_at
}
// GetLiveDomain gets the live_domain property value. The live_domain property
// returns a *string when successful
func (m *App) GetLiveDomain()(*string) {
    return m.live_domain
}
// GetLiveUrl gets the live_url property value. The live_url property
// returns a *string when successful
func (m *App) GetLiveUrl()(*string) {
    return m.live_url
}
// GetLiveUrlBase gets the live_url_base property value. The live_url_base property
// returns a *string when successful
func (m *App) GetLiveUrlBase()(*string) {
    return m.live_url_base
}
// GetOwnerUuid gets the owner_uuid property value. The owner_uuid property
// returns a *string when successful
func (m *App) GetOwnerUuid()(*string) {
    return m.owner_uuid
}
// GetPendingDeployment gets the pending_deployment property value. The pending_deployment property
// returns a Apps_deploymentable when successful
func (m *App) GetPendingDeployment()(Apps_deploymentable) {
    return m.pending_deployment
}
// GetPinnedDeployment gets the pinned_deployment property value. The pinned_deployment property
// returns a Apps_deploymentable when successful
func (m *App) GetPinnedDeployment()(Apps_deploymentable) {
    return m.pinned_deployment
}
// GetProjectId gets the project_id property value. Requires `project:read` scope.
// returns a *string when successful
func (m *App) GetProjectId()(*string) {
    return m.project_id
}
// GetRegion gets the region property value. The region property
// returns a Apps_regionable when successful
func (m *App) GetRegion()(Apps_regionable) {
    return m.region
}
// GetSpec gets the spec property value. The desired configuration of an application.
// returns a App_specable when successful
func (m *App) GetSpec()(App_specable) {
    return m.spec
}
// GetTierSlug gets the tier_slug property value. The tier_slug property
// returns a *string when successful
func (m *App) GetTierSlug()(*string) {
    return m.tier_slug
}
// GetUpdatedAt gets the updated_at property value. The updated_at property
// returns a *Time when successful
func (m *App) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updated_at
}
// GetVpc gets the vpc property value. The vpc property
// returns a Apps_vpcable when successful
func (m *App) GetVpc()(Apps_vpcable) {
    return m.vpc
}
// Serialize serializes information the current object
func (m *App) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("active_deployment", m.GetActiveDeployment())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("in_progress_deployment", m.GetInProgressDeployment())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("pending_deployment", m.GetPendingDeployment())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("pinned_deployment", m.GetPinnedDeployment())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("region", m.GetRegion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("spec", m.GetSpec())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActiveDeployment sets the active_deployment property value. The active_deployment property
func (m *App) SetActiveDeployment(value Apps_deploymentable)() {
    m.active_deployment = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *App) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the created_at property value. The created_at property
func (m *App) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetDedicatedIps sets the dedicated_ips property value. The dedicated_ips property
func (m *App) SetDedicatedIps(value []Apps_dedicated_egress_ipable)() {
    m.dedicated_ips = value
}
// SetDefaultIngress sets the default_ingress property value. The default_ingress property
func (m *App) SetDefaultIngress(value *string)() {
    m.default_ingress = value
}
// SetDomains sets the domains property value. The domains property
func (m *App) SetDomains(value []Apps_domainable)() {
    m.domains = value
}
// SetId sets the id property value. The id property
func (m *App) SetId(value *string)() {
    m.id = value
}
// SetInProgressDeployment sets the in_progress_deployment property value. The in_progress_deployment property
func (m *App) SetInProgressDeployment(value Apps_deploymentable)() {
    m.in_progress_deployment = value
}
// SetLastDeploymentCreatedAt sets the last_deployment_created_at property value. The last_deployment_created_at property
func (m *App) SetLastDeploymentCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.last_deployment_created_at = value
}
// SetLiveDomain sets the live_domain property value. The live_domain property
func (m *App) SetLiveDomain(value *string)() {
    m.live_domain = value
}
// SetLiveUrl sets the live_url property value. The live_url property
func (m *App) SetLiveUrl(value *string)() {
    m.live_url = value
}
// SetLiveUrlBase sets the live_url_base property value. The live_url_base property
func (m *App) SetLiveUrlBase(value *string)() {
    m.live_url_base = value
}
// SetOwnerUuid sets the owner_uuid property value. The owner_uuid property
func (m *App) SetOwnerUuid(value *string)() {
    m.owner_uuid = value
}
// SetPendingDeployment sets the pending_deployment property value. The pending_deployment property
func (m *App) SetPendingDeployment(value Apps_deploymentable)() {
    m.pending_deployment = value
}
// SetPinnedDeployment sets the pinned_deployment property value. The pinned_deployment property
func (m *App) SetPinnedDeployment(value Apps_deploymentable)() {
    m.pinned_deployment = value
}
// SetProjectId sets the project_id property value. Requires `project:read` scope.
func (m *App) SetProjectId(value *string)() {
    m.project_id = value
}
// SetRegion sets the region property value. The region property
func (m *App) SetRegion(value Apps_regionable)() {
    m.region = value
}
// SetSpec sets the spec property value. The desired configuration of an application.
func (m *App) SetSpec(value App_specable)() {
    m.spec = value
}
// SetTierSlug sets the tier_slug property value. The tier_slug property
func (m *App) SetTierSlug(value *string)() {
    m.tier_slug = value
}
// SetUpdatedAt sets the updated_at property value. The updated_at property
func (m *App) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updated_at = value
}
// SetVpc sets the vpc property value. The vpc property
func (m *App) SetVpc(value Apps_vpcable)() {
    m.vpc = value
}
type Appable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActiveDeployment()(Apps_deploymentable)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetDedicatedIps()([]Apps_dedicated_egress_ipable)
    GetDefaultIngress()(*string)
    GetDomains()([]Apps_domainable)
    GetId()(*string)
    GetInProgressDeployment()(Apps_deploymentable)
    GetLastDeploymentCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetLiveDomain()(*string)
    GetLiveUrl()(*string)
    GetLiveUrlBase()(*string)
    GetOwnerUuid()(*string)
    GetPendingDeployment()(Apps_deploymentable)
    GetPinnedDeployment()(Apps_deploymentable)
    GetProjectId()(*string)
    GetRegion()(Apps_regionable)
    GetSpec()(App_specable)
    GetTierSlug()(*string)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetVpc()(Apps_vpcable)
    SetActiveDeployment(value Apps_deploymentable)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetDedicatedIps(value []Apps_dedicated_egress_ipable)()
    SetDefaultIngress(value *string)()
    SetDomains(value []Apps_domainable)()
    SetId(value *string)()
    SetInProgressDeployment(value Apps_deploymentable)()
    SetLastDeploymentCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetLiveDomain(value *string)()
    SetLiveUrl(value *string)()
    SetLiveUrlBase(value *string)()
    SetOwnerUuid(value *string)()
    SetPendingDeployment(value Apps_deploymentable)()
    SetPinnedDeployment(value Apps_deploymentable)()
    SetProjectId(value *string)()
    SetRegion(value Apps_regionable)()
    SetSpec(value App_specable)()
    SetTierSlug(value *string)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetVpc(value Apps_vpcable)()
}
