// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// App_log_destination_datadog_spec dataDog configuration.
type App_log_destination_datadog_spec struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Datadog API key.
    api_key *string
    // Datadog HTTP log intake endpoint.
    endpoint *string
}
// NewApp_log_destination_datadog_spec instantiates a new App_log_destination_datadog_spec and sets the default values.
func NewApp_log_destination_datadog_spec()(*App_log_destination_datadog_spec) {
    m := &App_log_destination_datadog_spec{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateApp_log_destination_datadog_specFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateApp_log_destination_datadog_specFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewApp_log_destination_datadog_spec(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *App_log_destination_datadog_spec) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetApiKey gets the api_key property value. Datadog API key.
// returns a *string when successful
func (m *App_log_destination_datadog_spec) GetApiKey()(*string) {
    return m.api_key
}
// GetEndpoint gets the endpoint property value. Datadog HTTP log intake endpoint.
// returns a *string when successful
func (m *App_log_destination_datadog_spec) GetEndpoint()(*string) {
    return m.endpoint
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *App_log_destination_datadog_spec) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["api_key"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetApiKey(val)
        }
        return nil
    }
    res["endpoint"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndpoint(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *App_log_destination_datadog_spec) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("api_key", m.GetApiKey())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("endpoint", m.GetEndpoint())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *App_log_destination_datadog_spec) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetApiKey sets the api_key property value. Datadog API key.
func (m *App_log_destination_datadog_spec) SetApiKey(value *string)() {
    m.api_key = value
}
// SetEndpoint sets the endpoint property value. Datadog HTTP log intake endpoint.
func (m *App_log_destination_datadog_spec) SetEndpoint(value *string)() {
    m.endpoint = value
}
type App_log_destination_datadog_specable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetApiKey()(*string)
    GetEndpoint()(*string)
    SetApiKey(value *string)()
    SetEndpoint(value *string)()
}
