// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type App_alert_progress struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The steps property
    steps []App_alert_progress_stepable
}
// NewApp_alert_progress instantiates a new App_alert_progress and sets the default values.
func NewApp_alert_progress()(*App_alert_progress) {
    m := &App_alert_progress{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateApp_alert_progressFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateApp_alert_progressFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewApp_alert_progress(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *App_alert_progress) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *App_alert_progress) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["steps"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateApp_alert_progress_stepFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]App_alert_progress_stepable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(App_alert_progress_stepable)
                }
            }
            m.SetSteps(res)
        }
        return nil
    }
    return res
}
// GetSteps gets the steps property value. The steps property
// returns a []App_alert_progress_stepable when successful
func (m *App_alert_progress) GetSteps()([]App_alert_progress_stepable) {
    return m.steps
}
// Serialize serializes information the current object
func (m *App_alert_progress) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetSteps() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSteps()))
        for i, v := range m.GetSteps() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("steps", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *App_alert_progress) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetSteps sets the steps property value. The steps property
func (m *App_alert_progress) SetSteps(value []App_alert_progress_stepable)() {
    m.steps = value
}
type App_alert_progressable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetSteps()([]App_alert_progress_stepable)
    SetSteps(value []App_alert_progress_stepable)()
}
