// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Associated_resource an objects containing information about a resource associated with a Droplet.
type Associated_resource struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The cost of the resource in USD per month if the resource is retained after the Droplet is destroyed.
    cost *string
    // The unique identifier for the resource associated with the Droplet.
    id *string
    // The name of the resource associated with the Droplet.
    name *string
}
// NewAssociated_resource instantiates a new Associated_resource and sets the default values.
func NewAssociated_resource()(*Associated_resource) {
    m := &Associated_resource{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAssociated_resourceFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAssociated_resourceFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAssociated_resource(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Associated_resource) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCost gets the cost property value. The cost of the resource in USD per month if the resource is retained after the Droplet is destroyed.
// returns a *string when successful
func (m *Associated_resource) GetCost()(*string) {
    return m.cost
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Associated_resource) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["cost"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCost(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The unique identifier for the resource associated with the Droplet.
// returns a *string when successful
func (m *Associated_resource) GetId()(*string) {
    return m.id
}
// GetName gets the name property value. The name of the resource associated with the Droplet.
// returns a *string when successful
func (m *Associated_resource) GetName()(*string) {
    return m.name
}
// Serialize serializes information the current object
func (m *Associated_resource) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("cost", m.GetCost())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Associated_resource) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCost sets the cost property value. The cost of the resource in USD per month if the resource is retained after the Droplet is destroyed.
func (m *Associated_resource) SetCost(value *string)() {
    m.cost = value
}
// SetId sets the id property value. The unique identifier for the resource associated with the Droplet.
func (m *Associated_resource) SetId(value *string)() {
    m.id = value
}
// SetName sets the name property value. The name of the resource associated with the Droplet.
func (m *Associated_resource) SetName(value *string)() {
    m.name = value
}
type Associated_resourceable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCost()(*string)
    GetId()(*string)
    GetName()(*string)
    SetCost(value *string)()
    SetId(value *string)()
    SetName(value *string)()
}
