// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Control_plane_firewall an object specifying the control plane firewall for the Kubernetes cluster. Control plane firewall is in early availability (invite only).
type Control_plane_firewall struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // An array of public addresses (IPv4 or CIDR) allowed to access the control plane.
    allowed_addresses []string
    // Indicates whether the control plane firewall is enabled.
    enabled *bool
}
// NewControl_plane_firewall instantiates a new Control_plane_firewall and sets the default values.
func NewControl_plane_firewall()(*Control_plane_firewall) {
    m := &Control_plane_firewall{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateControl_plane_firewallFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateControl_plane_firewallFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewControl_plane_firewall(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Control_plane_firewall) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAllowedAddresses gets the allowed_addresses property value. An array of public addresses (IPv4 or CIDR) allowed to access the control plane.
// returns a []string when successful
func (m *Control_plane_firewall) GetAllowedAddresses()([]string) {
    return m.allowed_addresses
}
// GetEnabled gets the enabled property value. Indicates whether the control plane firewall is enabled.
// returns a *bool when successful
func (m *Control_plane_firewall) GetEnabled()(*bool) {
    return m.enabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Control_plane_firewall) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["allowed_addresses"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetAllowedAddresses(res)
        }
        return nil
    }
    res["enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnabled(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *Control_plane_firewall) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAllowedAddresses() != nil {
        err := writer.WriteCollectionOfStringValues("allowed_addresses", m.GetAllowedAddresses())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enabled", m.GetEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Control_plane_firewall) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAllowedAddresses sets the allowed_addresses property value. An array of public addresses (IPv4 or CIDR) allowed to access the control plane.
func (m *Control_plane_firewall) SetAllowedAddresses(value []string)() {
    m.allowed_addresses = value
}
// SetEnabled sets the enabled property value. Indicates whether the control plane firewall is enabled.
func (m *Control_plane_firewall) SetEnabled(value *bool)() {
    m.enabled = value
}
type Control_plane_firewallable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAllowedAddresses()([]string)
    GetEnabled()(*bool)
    SetAllowedAddresses(value []string)()
    SetEnabled(value *bool)()
}
