// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Create_image_request request body for image generation.
type Create_image_request struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The background setting for the image generation. Supported values: transparent, opaque, auto.
    background *string
    // The model to use for image generation.
    model *string
    // The moderation setting for the image generation. Supported values: low, auto.
    moderation *string
    // The number of images to generate. Must be between 1 and 10.
    n *int32
    // The output compression level for the image generation (0-100).
    output_compression *int32
    // The output format for the image generation. Supported values: png, webp, jpeg.
    output_format *string
    // The number of partial image chunks to return during streaming generation. Defaults to 0. When stream=true, this must be greater than 0 to receive progressive updates of the image as it is being generated.
    partial_images *int32
    // A text description of the desired image(s). Supports up to 32,000 characters and provides automatic prompt optimization for best results.
    prompt *string
    // The quality of the image that will be generated. Supported values: auto, high, medium, low.
    quality *string
    // The size of the generated images. GPT-IMAGE-1 supports: auto (automatically select best size), 1536x1024 (landscape), 1024x1536 (portrait).
    size *Create_image_request_size
    // If set to true, partial image data will be streamed as the image is being generated. The response will be sent as server-sent events with partial image chunks. When stream is true, partial_images must be greater than 0.
    stream *bool
    // A unique identifier representing your end-user, which can help DigitalOcean to monitor and detect abuse.
    user *string
}
// NewCreate_image_request instantiates a new Create_image_request and sets the default values.
func NewCreate_image_request()(*Create_image_request) {
    m := &Create_image_request{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCreate_image_requestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCreate_image_requestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCreate_image_request(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Create_image_request) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetBackground gets the background property value. The background setting for the image generation. Supported values: transparent, opaque, auto.
// returns a *string when successful
func (m *Create_image_request) GetBackground()(*string) {
    return m.background
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Create_image_request) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["background"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBackground(val)
        }
        return nil
    }
    res["model"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModel(val)
        }
        return nil
    }
    res["moderation"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModeration(val)
        }
        return nil
    }
    res["n"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetN(val)
        }
        return nil
    }
    res["output_compression"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOutputCompression(val)
        }
        return nil
    }
    res["output_format"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOutputFormat(val)
        }
        return nil
    }
    res["partial_images"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPartialImages(val)
        }
        return nil
    }
    res["prompt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPrompt(val)
        }
        return nil
    }
    res["quality"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetQuality(val)
        }
        return nil
    }
    res["size"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseCreate_image_request_size)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSize(val.(*Create_image_request_size))
        }
        return nil
    }
    res["stream"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStream(val)
        }
        return nil
    }
    res["user"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUser(val)
        }
        return nil
    }
    return res
}
// GetModel gets the model property value. The model to use for image generation.
// returns a *string when successful
func (m *Create_image_request) GetModel()(*string) {
    return m.model
}
// GetModeration gets the moderation property value. The moderation setting for the image generation. Supported values: low, auto.
// returns a *string when successful
func (m *Create_image_request) GetModeration()(*string) {
    return m.moderation
}
// GetN gets the n property value. The number of images to generate. Must be between 1 and 10.
// returns a *int32 when successful
func (m *Create_image_request) GetN()(*int32) {
    return m.n
}
// GetOutputCompression gets the output_compression property value. The output compression level for the image generation (0-100).
// returns a *int32 when successful
func (m *Create_image_request) GetOutputCompression()(*int32) {
    return m.output_compression
}
// GetOutputFormat gets the output_format property value. The output format for the image generation. Supported values: png, webp, jpeg.
// returns a *string when successful
func (m *Create_image_request) GetOutputFormat()(*string) {
    return m.output_format
}
// GetPartialImages gets the partial_images property value. The number of partial image chunks to return during streaming generation. Defaults to 0. When stream=true, this must be greater than 0 to receive progressive updates of the image as it is being generated.
// returns a *int32 when successful
func (m *Create_image_request) GetPartialImages()(*int32) {
    return m.partial_images
}
// GetPrompt gets the prompt property value. A text description of the desired image(s). Supports up to 32,000 characters and provides automatic prompt optimization for best results.
// returns a *string when successful
func (m *Create_image_request) GetPrompt()(*string) {
    return m.prompt
}
// GetQuality gets the quality property value. The quality of the image that will be generated. Supported values: auto, high, medium, low.
// returns a *string when successful
func (m *Create_image_request) GetQuality()(*string) {
    return m.quality
}
// GetSize gets the size property value. The size of the generated images. GPT-IMAGE-1 supports: auto (automatically select best size), 1536x1024 (landscape), 1024x1536 (portrait).
// returns a *Create_image_request_size when successful
func (m *Create_image_request) GetSize()(*Create_image_request_size) {
    return m.size
}
// GetStream gets the stream property value. If set to true, partial image data will be streamed as the image is being generated. The response will be sent as server-sent events with partial image chunks. When stream is true, partial_images must be greater than 0.
// returns a *bool when successful
func (m *Create_image_request) GetStream()(*bool) {
    return m.stream
}
// GetUser gets the user property value. A unique identifier representing your end-user, which can help DigitalOcean to monitor and detect abuse.
// returns a *string when successful
func (m *Create_image_request) GetUser()(*string) {
    return m.user
}
// Serialize serializes information the current object
func (m *Create_image_request) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("background", m.GetBackground())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("model", m.GetModel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("moderation", m.GetModeration())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("n", m.GetN())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("output_compression", m.GetOutputCompression())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("output_format", m.GetOutputFormat())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("partial_images", m.GetPartialImages())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("prompt", m.GetPrompt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("quality", m.GetQuality())
        if err != nil {
            return err
        }
    }
    if m.GetSize() != nil {
        cast := (*m.GetSize()).String()
        err := writer.WriteStringValue("size", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("stream", m.GetStream())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("user", m.GetUser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Create_image_request) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetBackground sets the background property value. The background setting for the image generation. Supported values: transparent, opaque, auto.
func (m *Create_image_request) SetBackground(value *string)() {
    m.background = value
}
// SetModel sets the model property value. The model to use for image generation.
func (m *Create_image_request) SetModel(value *string)() {
    m.model = value
}
// SetModeration sets the moderation property value. The moderation setting for the image generation. Supported values: low, auto.
func (m *Create_image_request) SetModeration(value *string)() {
    m.moderation = value
}
// SetN sets the n property value. The number of images to generate. Must be between 1 and 10.
func (m *Create_image_request) SetN(value *int32)() {
    m.n = value
}
// SetOutputCompression sets the output_compression property value. The output compression level for the image generation (0-100).
func (m *Create_image_request) SetOutputCompression(value *int32)() {
    m.output_compression = value
}
// SetOutputFormat sets the output_format property value. The output format for the image generation. Supported values: png, webp, jpeg.
func (m *Create_image_request) SetOutputFormat(value *string)() {
    m.output_format = value
}
// SetPartialImages sets the partial_images property value. The number of partial image chunks to return during streaming generation. Defaults to 0. When stream=true, this must be greater than 0 to receive progressive updates of the image as it is being generated.
func (m *Create_image_request) SetPartialImages(value *int32)() {
    m.partial_images = value
}
// SetPrompt sets the prompt property value. A text description of the desired image(s). Supports up to 32,000 characters and provides automatic prompt optimization for best results.
func (m *Create_image_request) SetPrompt(value *string)() {
    m.prompt = value
}
// SetQuality sets the quality property value. The quality of the image that will be generated. Supported values: auto, high, medium, low.
func (m *Create_image_request) SetQuality(value *string)() {
    m.quality = value
}
// SetSize sets the size property value. The size of the generated images. GPT-IMAGE-1 supports: auto (automatically select best size), 1536x1024 (landscape), 1024x1536 (portrait).
func (m *Create_image_request) SetSize(value *Create_image_request_size)() {
    m.size = value
}
// SetStream sets the stream property value. If set to true, partial image data will be streamed as the image is being generated. The response will be sent as server-sent events with partial image chunks. When stream is true, partial_images must be greater than 0.
func (m *Create_image_request) SetStream(value *bool)() {
    m.stream = value
}
// SetUser sets the user property value. A unique identifier representing your end-user, which can help DigitalOcean to monitor and detect abuse.
func (m *Create_image_request) SetUser(value *string)() {
    m.user = value
}
type Create_image_requestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBackground()(*string)
    GetModel()(*string)
    GetModeration()(*string)
    GetN()(*int32)
    GetOutputCompression()(*int32)
    GetOutputFormat()(*string)
    GetPartialImages()(*int32)
    GetPrompt()(*string)
    GetQuality()(*string)
    GetSize()(*Create_image_request_size)
    GetStream()(*bool)
    GetUser()(*string)
    SetBackground(value *string)()
    SetModel(value *string)()
    SetModeration(value *string)()
    SetN(value *int32)()
    SetOutputCompression(value *int32)()
    SetOutputFormat(value *string)()
    SetPartialImages(value *int32)()
    SetPrompt(value *string)()
    SetQuality(value *string)()
    SetSize(value *Create_image_request_size)()
    SetStream(value *bool)()
    SetUser(value *string)()
}
