// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// The size of the generated images. GPT-IMAGE-1 supports: auto (automatically select best size), 1536x1024 (landscape), 1024x1536 (portrait).
type Create_image_request_size int

const (
    AUTO_CREATE_IMAGE_REQUEST_SIZE Create_image_request_size = iota
    ONEFIVETHREESIXX1024_CREATE_IMAGE_REQUEST_SIZE
    ONEZEROTWOFOURX1536_CREATE_IMAGE_REQUEST_SIZE
)

func (i Create_image_request_size) String() string {
    return []string{"auto", "1536x1024", "1024x1536"}[i]
}
func ParseCreate_image_request_size(v string) (any, error) {
    result := AUTO_CREATE_IMAGE_REQUEST_SIZE
    switch v {
        case "auto":
            result = AUTO_CREATE_IMAGE_REQUEST_SIZE
        case "1536x1024":
            result = ONEFIVETHREESIXX1024_CREATE_IMAGE_REQUEST_SIZE
        case "1024x1536":
            result = ONEZEROTWOFOURX1536_CREATE_IMAGE_REQUEST_SIZE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeCreate_image_request_size(values []Create_image_request_size) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Create_image_request_size) isMultiValue() bool {
    return false
}
