// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CustomModelSourceRef reference to the original source of the model
type CustomModelSourceRef struct {
    // Access level required for the model repository
    access_type *SourceRefAccessType
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Spaces bucket name
    bucket *string
    // Git commit SHA of the model version
    commit_sha *string
    // User-provided HuggingFace token for gated/private models (not persisted in source_ref)
    hf_token *string
    // Object prefix path in the bucket
    prefix *string
    // Spaces bucket region
    region *string
    // Huggingface repository identifier
    repo_id *string
}
// NewCustomModelSourceRef instantiates a new CustomModelSourceRef and sets the default values.
func NewCustomModelSourceRef()(*CustomModelSourceRef) {
    m := &CustomModelSourceRef{
    }
    access_typeValue := ACCESS_TYPE_UNSPECIFIED_SOURCEREFACCESSTYPE
    m.SetAccessType(&access_typeValue)
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCustomModelSourceRefFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCustomModelSourceRefFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCustomModelSourceRef(), nil
}
// GetAccessType gets the access_type property value. Access level required for the model repository
// returns a *SourceRefAccessType when successful
func (m *CustomModelSourceRef) GetAccessType()(*SourceRefAccessType) {
    return m.access_type
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CustomModelSourceRef) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetBucket gets the bucket property value. Spaces bucket name
// returns a *string when successful
func (m *CustomModelSourceRef) GetBucket()(*string) {
    return m.bucket
}
// GetCommitSha gets the commit_sha property value. Git commit SHA of the model version
// returns a *string when successful
func (m *CustomModelSourceRef) GetCommitSha()(*string) {
    return m.commit_sha
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CustomModelSourceRef) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["access_type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseSourceRefAccessType)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccessType(val.(*SourceRefAccessType))
        }
        return nil
    }
    res["bucket"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBucket(val)
        }
        return nil
    }
    res["commit_sha"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCommitSha(val)
        }
        return nil
    }
    res["hf_token"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHfToken(val)
        }
        return nil
    }
    res["prefix"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPrefix(val)
        }
        return nil
    }
    res["region"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRegion(val)
        }
        return nil
    }
    res["repo_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRepoId(val)
        }
        return nil
    }
    return res
}
// GetHfToken gets the hf_token property value. User-provided HuggingFace token for gated/private models (not persisted in source_ref)
// returns a *string when successful
func (m *CustomModelSourceRef) GetHfToken()(*string) {
    return m.hf_token
}
// GetPrefix gets the prefix property value. Object prefix path in the bucket
// returns a *string when successful
func (m *CustomModelSourceRef) GetPrefix()(*string) {
    return m.prefix
}
// GetRegion gets the region property value. Spaces bucket region
// returns a *string when successful
func (m *CustomModelSourceRef) GetRegion()(*string) {
    return m.region
}
// GetRepoId gets the repo_id property value. Huggingface repository identifier
// returns a *string when successful
func (m *CustomModelSourceRef) GetRepoId()(*string) {
    return m.repo_id
}
// Serialize serializes information the current object
func (m *CustomModelSourceRef) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAccessType() != nil {
        cast := (*m.GetAccessType()).String()
        err := writer.WriteStringValue("access_type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("bucket", m.GetBucket())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("commit_sha", m.GetCommitSha())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("hf_token", m.GetHfToken())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("prefix", m.GetPrefix())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("region", m.GetRegion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("repo_id", m.GetRepoId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAccessType sets the access_type property value. Access level required for the model repository
func (m *CustomModelSourceRef) SetAccessType(value *SourceRefAccessType)() {
    m.access_type = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CustomModelSourceRef) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetBucket sets the bucket property value. Spaces bucket name
func (m *CustomModelSourceRef) SetBucket(value *string)() {
    m.bucket = value
}
// SetCommitSha sets the commit_sha property value. Git commit SHA of the model version
func (m *CustomModelSourceRef) SetCommitSha(value *string)() {
    m.commit_sha = value
}
// SetHfToken sets the hf_token property value. User-provided HuggingFace token for gated/private models (not persisted in source_ref)
func (m *CustomModelSourceRef) SetHfToken(value *string)() {
    m.hf_token = value
}
// SetPrefix sets the prefix property value. Object prefix path in the bucket
func (m *CustomModelSourceRef) SetPrefix(value *string)() {
    m.prefix = value
}
// SetRegion sets the region property value. Spaces bucket region
func (m *CustomModelSourceRef) SetRegion(value *string)() {
    m.region = value
}
// SetRepoId sets the repo_id property value. Huggingface repository identifier
func (m *CustomModelSourceRef) SetRepoId(value *string)() {
    m.repo_id = value
}
type CustomModelSourceRefable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccessType()(*SourceRefAccessType)
    GetBucket()(*string)
    GetCommitSha()(*string)
    GetHfToken()(*string)
    GetPrefix()(*string)
    GetRegion()(*string)
    GetRepoId()(*string)
    SetAccessType(value *SourceRefAccessType)()
    SetBucket(value *string)()
    SetCommitSha(value *string)()
    SetHfToken(value *string)()
    SetPrefix(value *string)()
    SetRegion(value *string)()
    SetRepoId(value *string)()
}
