// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Dedicated_inference a Dedicated Inference instance.
type Dedicated_inference struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // When the Dedicated Inference was created.
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The endpoints property
    endpoints Dedicated_inference_endpointsable
    // Unique ID of the Dedicated Inference.
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // Pending deployment when status is provisioning or updating.
    pending_deployment_spec Pending_deployment_specable
    // DigitalOcean region where the Dedicated Inference is hosted.
    region *string
    // Structured configuration for a Dedicated Inference deployment.
    spec Dedicated_inference_specable
    // Current state of the Dedicated Inference.
    status *Dedicated_inference_status
    // When the Dedicated Inference was last updated.
    updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // VPC UUID of the Dedicated Inference.
    vpc_uuid *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
}
// NewDedicated_inference instantiates a new Dedicated_inference and sets the default values.
func NewDedicated_inference()(*Dedicated_inference) {
    m := &Dedicated_inference{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDedicated_inferenceFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDedicated_inferenceFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDedicated_inference(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Dedicated_inference) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the created_at property value. When the Dedicated Inference was created.
// returns a *Time when successful
func (m *Dedicated_inference) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetEndpoints gets the endpoints property value. The endpoints property
// returns a Dedicated_inference_endpointsable when successful
func (m *Dedicated_inference) GetEndpoints()(Dedicated_inference_endpointsable) {
    return m.endpoints
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Dedicated_inference) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["endpoints"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDedicated_inference_endpointsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndpoints(val.(Dedicated_inference_endpointsable))
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["pending_deployment_spec"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePending_deployment_specFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPendingDeploymentSpec(val.(Pending_deployment_specable))
        }
        return nil
    }
    res["region"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRegion(val)
        }
        return nil
    }
    res["spec"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDedicated_inference_specFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSpec(val.(Dedicated_inference_specable))
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseDedicated_inference_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*Dedicated_inference_status))
        }
        return nil
    }
    res["updated_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    res["vpc_uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVpcUuid(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. Unique ID of the Dedicated Inference.
// returns a *UUID when successful
func (m *Dedicated_inference) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetPendingDeploymentSpec gets the pending_deployment_spec property value. Pending deployment when status is provisioning or updating.
// returns a Pending_deployment_specable when successful
func (m *Dedicated_inference) GetPendingDeploymentSpec()(Pending_deployment_specable) {
    return m.pending_deployment_spec
}
// GetRegion gets the region property value. DigitalOcean region where the Dedicated Inference is hosted.
// returns a *string when successful
func (m *Dedicated_inference) GetRegion()(*string) {
    return m.region
}
// GetSpec gets the spec property value. Structured configuration for a Dedicated Inference deployment.
// returns a Dedicated_inference_specable when successful
func (m *Dedicated_inference) GetSpec()(Dedicated_inference_specable) {
    return m.spec
}
// GetStatus gets the status property value. Current state of the Dedicated Inference.
// returns a *Dedicated_inference_status when successful
func (m *Dedicated_inference) GetStatus()(*Dedicated_inference_status) {
    return m.status
}
// GetUpdatedAt gets the updated_at property value. When the Dedicated Inference was last updated.
// returns a *Time when successful
func (m *Dedicated_inference) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updated_at
}
// GetVpcUuid gets the vpc_uuid property value. VPC UUID of the Dedicated Inference.
// returns a *UUID when successful
func (m *Dedicated_inference) GetVpcUuid()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.vpc_uuid
}
// Serialize serializes information the current object
func (m *Dedicated_inference) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("pending_deployment_spec", m.GetPendingDeploymentSpec())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("spec", m.GetSpec())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Dedicated_inference) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the created_at property value. When the Dedicated Inference was created.
func (m *Dedicated_inference) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetEndpoints sets the endpoints property value. The endpoints property
func (m *Dedicated_inference) SetEndpoints(value Dedicated_inference_endpointsable)() {
    m.endpoints = value
}
// SetId sets the id property value. Unique ID of the Dedicated Inference.
func (m *Dedicated_inference) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetPendingDeploymentSpec sets the pending_deployment_spec property value. Pending deployment when status is provisioning or updating.
func (m *Dedicated_inference) SetPendingDeploymentSpec(value Pending_deployment_specable)() {
    m.pending_deployment_spec = value
}
// SetRegion sets the region property value. DigitalOcean region where the Dedicated Inference is hosted.
func (m *Dedicated_inference) SetRegion(value *string)() {
    m.region = value
}
// SetSpec sets the spec property value. Structured configuration for a Dedicated Inference deployment.
func (m *Dedicated_inference) SetSpec(value Dedicated_inference_specable)() {
    m.spec = value
}
// SetStatus sets the status property value. Current state of the Dedicated Inference.
func (m *Dedicated_inference) SetStatus(value *Dedicated_inference_status)() {
    m.status = value
}
// SetUpdatedAt sets the updated_at property value. When the Dedicated Inference was last updated.
func (m *Dedicated_inference) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updated_at = value
}
// SetVpcUuid sets the vpc_uuid property value. VPC UUID of the Dedicated Inference.
func (m *Dedicated_inference) SetVpcUuid(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.vpc_uuid = value
}
type Dedicated_inferenceable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetEndpoints()(Dedicated_inference_endpointsable)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetPendingDeploymentSpec()(Pending_deployment_specable)
    GetRegion()(*string)
    GetSpec()(Dedicated_inference_specable)
    GetStatus()(*Dedicated_inference_status)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetVpcUuid()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetEndpoints(value Dedicated_inference_endpointsable)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetPendingDeploymentSpec(value Pending_deployment_specable)()
    SetRegion(value *string)()
    SetSpec(value Dedicated_inference_specable)()
    SetStatus(value *Dedicated_inference_status)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetVpcUuid(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
}
