// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// The object type, which is always `embedding`.
type Embedding_data_item_object int

const (
    EMBEDDING_EMBEDDING_DATA_ITEM_OBJECT Embedding_data_item_object = iota
)

func (i Embedding_data_item_object) String() string {
    return []string{"embedding"}[i]
}
func ParseEmbedding_data_item_object(v string) (any, error) {
    result := EMBEDDING_EMBEDDING_DATA_ITEM_OBJECT
    switch v {
        case "embedding":
            result = EMBEDDING_EMBEDDING_DATA_ITEM_OBJECT
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeEmbedding_data_item_object(values []Embedding_data_item_object) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Embedding_data_item_object) isMultiValue() bool {
    return false
}
