// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Kafka_topic_verbose struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The config property
    config Kafka_topic_configable
    // The name of the Kafka topic.
    name *string
    // The partitions property
    partitions []Kafka_topic_partitionable
    // The number of nodes to replicate data across the cluster.
    replication_factor *int32
    // The state of the Kafka topic.
    state *Kafka_topic_verbose_state
}
// NewKafka_topic_verbose instantiates a new Kafka_topic_verbose and sets the default values.
func NewKafka_topic_verbose()(*Kafka_topic_verbose) {
    m := &Kafka_topic_verbose{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateKafka_topic_verboseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateKafka_topic_verboseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewKafka_topic_verbose(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Kafka_topic_verbose) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetConfig gets the config property value. The config property
// returns a Kafka_topic_configable when successful
func (m *Kafka_topic_verbose) GetConfig()(Kafka_topic_configable) {
    return m.config
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Kafka_topic_verbose) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["config"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateKafka_topic_configFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetConfig(val.(Kafka_topic_configable))
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["partitions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateKafka_topic_partitionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Kafka_topic_partitionable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Kafka_topic_partitionable)
                }
            }
            m.SetPartitions(res)
        }
        return nil
    }
    res["replication_factor"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReplicationFactor(val)
        }
        return nil
    }
    res["state"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseKafka_topic_verbose_state)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetState(val.(*Kafka_topic_verbose_state))
        }
        return nil
    }
    return res
}
// GetName gets the name property value. The name of the Kafka topic.
// returns a *string when successful
func (m *Kafka_topic_verbose) GetName()(*string) {
    return m.name
}
// GetPartitions gets the partitions property value. The partitions property
// returns a []Kafka_topic_partitionable when successful
func (m *Kafka_topic_verbose) GetPartitions()([]Kafka_topic_partitionable) {
    return m.partitions
}
// GetReplicationFactor gets the replication_factor property value. The number of nodes to replicate data across the cluster.
// returns a *int32 when successful
func (m *Kafka_topic_verbose) GetReplicationFactor()(*int32) {
    return m.replication_factor
}
// GetState gets the state property value. The state of the Kafka topic.
// returns a *Kafka_topic_verbose_state when successful
func (m *Kafka_topic_verbose) GetState()(*Kafka_topic_verbose_state) {
    return m.state
}
// Serialize serializes information the current object
func (m *Kafka_topic_verbose) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("config", m.GetConfig())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    if m.GetPartitions() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPartitions()))
        for i, v := range m.GetPartitions() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("partitions", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("replication_factor", m.GetReplicationFactor())
        if err != nil {
            return err
        }
    }
    if m.GetState() != nil {
        cast := (*m.GetState()).String()
        err := writer.WriteStringValue("state", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Kafka_topic_verbose) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetConfig sets the config property value. The config property
func (m *Kafka_topic_verbose) SetConfig(value Kafka_topic_configable)() {
    m.config = value
}
// SetName sets the name property value. The name of the Kafka topic.
func (m *Kafka_topic_verbose) SetName(value *string)() {
    m.name = value
}
// SetPartitions sets the partitions property value. The partitions property
func (m *Kafka_topic_verbose) SetPartitions(value []Kafka_topic_partitionable)() {
    m.partitions = value
}
// SetReplicationFactor sets the replication_factor property value. The number of nodes to replicate data across the cluster.
func (m *Kafka_topic_verbose) SetReplicationFactor(value *int32)() {
    m.replication_factor = value
}
// SetState sets the state property value. The state of the Kafka topic.
func (m *Kafka_topic_verbose) SetState(value *Kafka_topic_verbose_state)() {
    m.state = value
}
type Kafka_topic_verboseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetConfig()(Kafka_topic_configable)
    GetName()(*string)
    GetPartitions()([]Kafka_topic_partitionable)
    GetReplicationFactor()(*int32)
    GetState()(*Kafka_topic_verbose_state)
    SetConfig(value Kafka_topic_configable)()
    SetName(value *string)()
    SetPartitions(value []Kafka_topic_partitionable)()
    SetReplicationFactor(value *int32)()
    SetState(value *Kafka_topic_verbose_state)()
}
