// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Load_balancer_base struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // This field has been deprecated. You can no longer specify an algorithm for load balancers.
    // Deprecated: 
    algorithm *Load_balancer_base_algorithm
    // A time value given in ISO8601 combined date and time format that represents when the load balancer was created.
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // A boolean value indicating whether to disable automatic DNS record creation for Let's Encrypt certificates that are added to the load balancer.
    disable_lets_encrypt_dns_records *bool
    // An array of objects specifying the domain configurations for a Global load balancer.
    domains []Domainsable
    // A boolean value indicating whether HTTP keepalive connections are maintained to target Droplets.
    enable_backend_keepalive *bool
    // A boolean value indicating whether PROXY Protocol is in use.
    enable_proxy_protocol *bool
    // An object specifying allow and deny rules to control traffic to the load balancer.
    firewall Lb_firewallable
    // An array of objects specifying the forwarding rules for a load balancer.
    forwarding_rules []Forwarding_ruleable
    // An object specifying forwarding configurations for a Global load balancer.
    glb_settings Glb_settingsable
    // An object specifying health check settings for the load balancer.
    health_check Health_checkable
    // An integer value which configures the idle timeout for HTTP requests to the target droplets.
    http_idle_timeout_seconds *int32
    // A unique ID that can be used to identify and reference a load balancer.
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // An attribute containing the public-facing IP address of the load balancer.
    ip *string
    // An attribute containing the public-facing IPv6 address of the load balancer.
    ipv6 *string
    // A human-readable name for a load balancer instance.
    name *string
    // A string indicating whether the load balancer should be external or internal. Internal load balancers have no public IPs and are only accessible to resources on the same VPC network. This property cannot be updated after creating the load balancer.
    network *Load_balancer_base_network
    // A string indicating whether the load balancer will support IPv4 or both IPv4 and IPv6 networking. This property cannot be updated after creating the load balancer.
    network_stack *Load_balancer_base_network_stack
    // The ID of the project that the load balancer is associated with. If no ID is provided at creation, the load balancer associates with the user's default project. If an invalid project ID is provided, the load balancer will not be created.
    project_id *string
    // A boolean value indicating whether HTTP requests to the load balancer on port 80 will be redirected to HTTPS on port 443.
    redirect_http_to_https *bool
    // This field has been replaced by the `size_unit` field for all regions except in AMS2, NYC2, and SFO1. Each available load balancer size now equates to the load balancer having a set number of nodes.* `lb-small` = 1 node* `lb-medium` = 3 nodes* `lb-large` = 6 nodesYou can resize load balancers after creation up to once per hour. You cannot resize a load balancer within the first hour of its creation.
    // Deprecated: 
    size *Load_balancer_base_size
    // How many nodes the load balancer contains. Each additional node increases the load balancer's ability to manage more connections. Load balancers can be scaled up or down, and you can change the number of nodes after creation up to once per hour. This field is currently not available in the AMS2, NYC2, or SFO1 regions. Use the `size` field to scale load balancers that reside in these regions.
    size_unit *int32
    // A status string indicating the current state of the load balancer. This can be `new`, `active`, or `errored`.
    status *Load_balancer_base_status
    // An object specifying sticky sessions settings for the load balancer.
    sticky_sessions Sticky_sessionsable
    // An array containing the UUIDs of the Regional load balancers to be used as target backends for a Global load balancer.
    target_load_balancer_ids []string
    // A string indicating the policy for the TLS cipher suites used by the load balancer. The possible values are `DEFAULT` or `STRONG`. The default value is `DEFAULT`.
    tls_cipher_policy *Load_balancer_base_tls_cipher_policy
    // A string indicating whether the load balancer should be a standard regional HTTP load balancer, a regional network load balancer that routes traffic at the TCP/UDP transport layer, or a global load balancer.
    typeEscaped *Load_balancer_base_type
    // A string specifying the UUID of the VPC to which the load balancer is assigned.
    vpc_uuid *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
}
// NewLoad_balancer_base instantiates a new Load_balancer_base and sets the default values.
func NewLoad_balancer_base()(*Load_balancer_base) {
    m := &Load_balancer_base{
    }
    m.SetAdditionalData(make(map[string]any))
    algorithmValue := ROUND_ROBIN_LOAD_BALANCER_BASE_ALGORITHM
    m.SetAlgorithm(&algorithmValue)
    networkValue := EXTERNAL_LOAD_BALANCER_BASE_NETWORK
    m.SetNetwork(&networkValue)
    network_stackValue := IPV4_LOAD_BALANCER_BASE_NETWORK_STACK
    m.SetNetworkStack(&network_stackValue)
    sizeValue := LBSMALL_LOAD_BALANCER_BASE_SIZE
    m.SetSize(&sizeValue)
    tls_cipher_policyValue := DEFAULT_LOAD_BALANCER_BASE_TLS_CIPHER_POLICY
    m.SetTlsCipherPolicy(&tls_cipher_policyValue)
    typeEscapedValue := REGIONAL_LOAD_BALANCER_BASE_TYPE
    m.SetTypeEscaped(&typeEscapedValue)
    return m
}
// CreateLoad_balancer_baseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLoad_balancer_baseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewLoad_balancer_base(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Load_balancer_base) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAlgorithm gets the algorithm property value. This field has been deprecated. You can no longer specify an algorithm for load balancers.
// Deprecated: 
// returns a *Load_balancer_base_algorithm when successful
func (m *Load_balancer_base) GetAlgorithm()(*Load_balancer_base_algorithm) {
    return m.algorithm
}
// GetCreatedAt gets the created_at property value. A time value given in ISO8601 combined date and time format that represents when the load balancer was created.
// returns a *Time when successful
func (m *Load_balancer_base) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetDisableLetsEncryptDnsRecords gets the disable_lets_encrypt_dns_records property value. A boolean value indicating whether to disable automatic DNS record creation for Let's Encrypt certificates that are added to the load balancer.
// returns a *bool when successful
func (m *Load_balancer_base) GetDisableLetsEncryptDnsRecords()(*bool) {
    return m.disable_lets_encrypt_dns_records
}
// GetDomains gets the domains property value. An array of objects specifying the domain configurations for a Global load balancer.
// returns a []Domainsable when successful
func (m *Load_balancer_base) GetDomains()([]Domainsable) {
    return m.domains
}
// GetEnableBackendKeepalive gets the enable_backend_keepalive property value. A boolean value indicating whether HTTP keepalive connections are maintained to target Droplets.
// returns a *bool when successful
func (m *Load_balancer_base) GetEnableBackendKeepalive()(*bool) {
    return m.enable_backend_keepalive
}
// GetEnableProxyProtocol gets the enable_proxy_protocol property value. A boolean value indicating whether PROXY Protocol is in use.
// returns a *bool when successful
func (m *Load_balancer_base) GetEnableProxyProtocol()(*bool) {
    return m.enable_proxy_protocol
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Load_balancer_base) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["algorithm"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLoad_balancer_base_algorithm)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAlgorithm(val.(*Load_balancer_base_algorithm))
        }
        return nil
    }
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["disable_lets_encrypt_dns_records"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDisableLetsEncryptDnsRecords(val)
        }
        return nil
    }
    res["domains"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateDomainsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Domainsable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Domainsable)
                }
            }
            m.SetDomains(res)
        }
        return nil
    }
    res["enable_backend_keepalive"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnableBackendKeepalive(val)
        }
        return nil
    }
    res["enable_proxy_protocol"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnableProxyProtocol(val)
        }
        return nil
    }
    res["firewall"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateLb_firewallFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFirewall(val.(Lb_firewallable))
        }
        return nil
    }
    res["forwarding_rules"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateForwarding_ruleFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Forwarding_ruleable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Forwarding_ruleable)
                }
            }
            m.SetForwardingRules(res)
        }
        return nil
    }
    res["glb_settings"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateGlb_settingsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGlbSettings(val.(Glb_settingsable))
        }
        return nil
    }
    res["health_check"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateHealth_checkFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHealthCheck(val.(Health_checkable))
        }
        return nil
    }
    res["http_idle_timeout_seconds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHttpIdleTimeoutSeconds(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["ip"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIp(val)
        }
        return nil
    }
    res["ipv6"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIpv6(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["network"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLoad_balancer_base_network)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNetwork(val.(*Load_balancer_base_network))
        }
        return nil
    }
    res["network_stack"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLoad_balancer_base_network_stack)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNetworkStack(val.(*Load_balancer_base_network_stack))
        }
        return nil
    }
    res["project_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProjectId(val)
        }
        return nil
    }
    res["redirect_http_to_https"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRedirectHttpToHttps(val)
        }
        return nil
    }
    res["size"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLoad_balancer_base_size)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSize(val.(*Load_balancer_base_size))
        }
        return nil
    }
    res["size_unit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSizeUnit(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLoad_balancer_base_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*Load_balancer_base_status))
        }
        return nil
    }
    res["sticky_sessions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSticky_sessionsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStickySessions(val.(Sticky_sessionsable))
        }
        return nil
    }
    res["target_load_balancer_ids"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetTargetLoadBalancerIds(res)
        }
        return nil
    }
    res["tls_cipher_policy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLoad_balancer_base_tls_cipher_policy)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTlsCipherPolicy(val.(*Load_balancer_base_tls_cipher_policy))
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLoad_balancer_base_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*Load_balancer_base_type))
        }
        return nil
    }
    res["vpc_uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVpcUuid(val)
        }
        return nil
    }
    return res
}
// GetFirewall gets the firewall property value. An object specifying allow and deny rules to control traffic to the load balancer.
// returns a Lb_firewallable when successful
func (m *Load_balancer_base) GetFirewall()(Lb_firewallable) {
    return m.firewall
}
// GetForwardingRules gets the forwarding_rules property value. An array of objects specifying the forwarding rules for a load balancer.
// returns a []Forwarding_ruleable when successful
func (m *Load_balancer_base) GetForwardingRules()([]Forwarding_ruleable) {
    return m.forwarding_rules
}
// GetGlbSettings gets the glb_settings property value. An object specifying forwarding configurations for a Global load balancer.
// returns a Glb_settingsable when successful
func (m *Load_balancer_base) GetGlbSettings()(Glb_settingsable) {
    return m.glb_settings
}
// GetHealthCheck gets the health_check property value. An object specifying health check settings for the load balancer.
// returns a Health_checkable when successful
func (m *Load_balancer_base) GetHealthCheck()(Health_checkable) {
    return m.health_check
}
// GetHttpIdleTimeoutSeconds gets the http_idle_timeout_seconds property value. An integer value which configures the idle timeout for HTTP requests to the target droplets.
// returns a *int32 when successful
func (m *Load_balancer_base) GetHttpIdleTimeoutSeconds()(*int32) {
    return m.http_idle_timeout_seconds
}
// GetId gets the id property value. A unique ID that can be used to identify and reference a load balancer.
// returns a *UUID when successful
func (m *Load_balancer_base) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetIp gets the ip property value. An attribute containing the public-facing IP address of the load balancer.
// returns a *string when successful
func (m *Load_balancer_base) GetIp()(*string) {
    return m.ip
}
// GetIpv6 gets the ipv6 property value. An attribute containing the public-facing IPv6 address of the load balancer.
// returns a *string when successful
func (m *Load_balancer_base) GetIpv6()(*string) {
    return m.ipv6
}
// GetName gets the name property value. A human-readable name for a load balancer instance.
// returns a *string when successful
func (m *Load_balancer_base) GetName()(*string) {
    return m.name
}
// GetNetwork gets the network property value. A string indicating whether the load balancer should be external or internal. Internal load balancers have no public IPs and are only accessible to resources on the same VPC network. This property cannot be updated after creating the load balancer.
// returns a *Load_balancer_base_network when successful
func (m *Load_balancer_base) GetNetwork()(*Load_balancer_base_network) {
    return m.network
}
// GetNetworkStack gets the network_stack property value. A string indicating whether the load balancer will support IPv4 or both IPv4 and IPv6 networking. This property cannot be updated after creating the load balancer.
// returns a *Load_balancer_base_network_stack when successful
func (m *Load_balancer_base) GetNetworkStack()(*Load_balancer_base_network_stack) {
    return m.network_stack
}
// GetProjectId gets the project_id property value. The ID of the project that the load balancer is associated with. If no ID is provided at creation, the load balancer associates with the user's default project. If an invalid project ID is provided, the load balancer will not be created.
// returns a *string when successful
func (m *Load_balancer_base) GetProjectId()(*string) {
    return m.project_id
}
// GetRedirectHttpToHttps gets the redirect_http_to_https property value. A boolean value indicating whether HTTP requests to the load balancer on port 80 will be redirected to HTTPS on port 443.
// returns a *bool when successful
func (m *Load_balancer_base) GetRedirectHttpToHttps()(*bool) {
    return m.redirect_http_to_https
}
// GetSize gets the size property value. This field has been replaced by the `size_unit` field for all regions except in AMS2, NYC2, and SFO1. Each available load balancer size now equates to the load balancer having a set number of nodes.* `lb-small` = 1 node* `lb-medium` = 3 nodes* `lb-large` = 6 nodesYou can resize load balancers after creation up to once per hour. You cannot resize a load balancer within the first hour of its creation.
// Deprecated: 
// returns a *Load_balancer_base_size when successful
func (m *Load_balancer_base) GetSize()(*Load_balancer_base_size) {
    return m.size
}
// GetSizeUnit gets the size_unit property value. How many nodes the load balancer contains. Each additional node increases the load balancer's ability to manage more connections. Load balancers can be scaled up or down, and you can change the number of nodes after creation up to once per hour. This field is currently not available in the AMS2, NYC2, or SFO1 regions. Use the `size` field to scale load balancers that reside in these regions.
// returns a *int32 when successful
func (m *Load_balancer_base) GetSizeUnit()(*int32) {
    return m.size_unit
}
// GetStatus gets the status property value. A status string indicating the current state of the load balancer. This can be `new`, `active`, or `errored`.
// returns a *Load_balancer_base_status when successful
func (m *Load_balancer_base) GetStatus()(*Load_balancer_base_status) {
    return m.status
}
// GetStickySessions gets the sticky_sessions property value. An object specifying sticky sessions settings for the load balancer.
// returns a Sticky_sessionsable when successful
func (m *Load_balancer_base) GetStickySessions()(Sticky_sessionsable) {
    return m.sticky_sessions
}
// GetTargetLoadBalancerIds gets the target_load_balancer_ids property value. An array containing the UUIDs of the Regional load balancers to be used as target backends for a Global load balancer.
// returns a []string when successful
func (m *Load_balancer_base) GetTargetLoadBalancerIds()([]string) {
    return m.target_load_balancer_ids
}
// GetTlsCipherPolicy gets the tls_cipher_policy property value. A string indicating the policy for the TLS cipher suites used by the load balancer. The possible values are `DEFAULT` or `STRONG`. The default value is `DEFAULT`.
// returns a *Load_balancer_base_tls_cipher_policy when successful
func (m *Load_balancer_base) GetTlsCipherPolicy()(*Load_balancer_base_tls_cipher_policy) {
    return m.tls_cipher_policy
}
// GetTypeEscaped gets the type property value. A string indicating whether the load balancer should be a standard regional HTTP load balancer, a regional network load balancer that routes traffic at the TCP/UDP transport layer, or a global load balancer.
// returns a *Load_balancer_base_type when successful
func (m *Load_balancer_base) GetTypeEscaped()(*Load_balancer_base_type) {
    return m.typeEscaped
}
// GetVpcUuid gets the vpc_uuid property value. A string specifying the UUID of the VPC to which the load balancer is assigned.
// returns a *UUID when successful
func (m *Load_balancer_base) GetVpcUuid()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.vpc_uuid
}
// Serialize serializes information the current object
func (m *Load_balancer_base) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAlgorithm() != nil {
        cast := (*m.GetAlgorithm()).String()
        err := writer.WriteStringValue("algorithm", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("disable_lets_encrypt_dns_records", m.GetDisableLetsEncryptDnsRecords())
        if err != nil {
            return err
        }
    }
    if m.GetDomains() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetDomains()))
        for i, v := range m.GetDomains() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("domains", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enable_backend_keepalive", m.GetEnableBackendKeepalive())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enable_proxy_protocol", m.GetEnableProxyProtocol())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("firewall", m.GetFirewall())
        if err != nil {
            return err
        }
    }
    if m.GetForwardingRules() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetForwardingRules()))
        for i, v := range m.GetForwardingRules() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("forwarding_rules", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("glb_settings", m.GetGlbSettings())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("health_check", m.GetHealthCheck())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("http_idle_timeout_seconds", m.GetHttpIdleTimeoutSeconds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    if m.GetNetwork() != nil {
        cast := (*m.GetNetwork()).String()
        err := writer.WriteStringValue("network", &cast)
        if err != nil {
            return err
        }
    }
    if m.GetNetworkStack() != nil {
        cast := (*m.GetNetworkStack()).String()
        err := writer.WriteStringValue("network_stack", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("project_id", m.GetProjectId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("redirect_http_to_https", m.GetRedirectHttpToHttps())
        if err != nil {
            return err
        }
    }
    if m.GetSize() != nil {
        cast := (*m.GetSize()).String()
        err := writer.WriteStringValue("size", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("size_unit", m.GetSizeUnit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("sticky_sessions", m.GetStickySessions())
        if err != nil {
            return err
        }
    }
    if m.GetTargetLoadBalancerIds() != nil {
        err := writer.WriteCollectionOfStringValues("target_load_balancer_ids", m.GetTargetLoadBalancerIds())
        if err != nil {
            return err
        }
    }
    if m.GetTlsCipherPolicy() != nil {
        cast := (*m.GetTlsCipherPolicy()).String()
        err := writer.WriteStringValue("tls_cipher_policy", &cast)
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("vpc_uuid", m.GetVpcUuid())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Load_balancer_base) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAlgorithm sets the algorithm property value. This field has been deprecated. You can no longer specify an algorithm for load balancers.
// Deprecated: 
func (m *Load_balancer_base) SetAlgorithm(value *Load_balancer_base_algorithm)() {
    m.algorithm = value
}
// SetCreatedAt sets the created_at property value. A time value given in ISO8601 combined date and time format that represents when the load balancer was created.
func (m *Load_balancer_base) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetDisableLetsEncryptDnsRecords sets the disable_lets_encrypt_dns_records property value. A boolean value indicating whether to disable automatic DNS record creation for Let's Encrypt certificates that are added to the load balancer.
func (m *Load_balancer_base) SetDisableLetsEncryptDnsRecords(value *bool)() {
    m.disable_lets_encrypt_dns_records = value
}
// SetDomains sets the domains property value. An array of objects specifying the domain configurations for a Global load balancer.
func (m *Load_balancer_base) SetDomains(value []Domainsable)() {
    m.domains = value
}
// SetEnableBackendKeepalive sets the enable_backend_keepalive property value. A boolean value indicating whether HTTP keepalive connections are maintained to target Droplets.
func (m *Load_balancer_base) SetEnableBackendKeepalive(value *bool)() {
    m.enable_backend_keepalive = value
}
// SetEnableProxyProtocol sets the enable_proxy_protocol property value. A boolean value indicating whether PROXY Protocol is in use.
func (m *Load_balancer_base) SetEnableProxyProtocol(value *bool)() {
    m.enable_proxy_protocol = value
}
// SetFirewall sets the firewall property value. An object specifying allow and deny rules to control traffic to the load balancer.
func (m *Load_balancer_base) SetFirewall(value Lb_firewallable)() {
    m.firewall = value
}
// SetForwardingRules sets the forwarding_rules property value. An array of objects specifying the forwarding rules for a load balancer.
func (m *Load_balancer_base) SetForwardingRules(value []Forwarding_ruleable)() {
    m.forwarding_rules = value
}
// SetGlbSettings sets the glb_settings property value. An object specifying forwarding configurations for a Global load balancer.
func (m *Load_balancer_base) SetGlbSettings(value Glb_settingsable)() {
    m.glb_settings = value
}
// SetHealthCheck sets the health_check property value. An object specifying health check settings for the load balancer.
func (m *Load_balancer_base) SetHealthCheck(value Health_checkable)() {
    m.health_check = value
}
// SetHttpIdleTimeoutSeconds sets the http_idle_timeout_seconds property value. An integer value which configures the idle timeout for HTTP requests to the target droplets.
func (m *Load_balancer_base) SetHttpIdleTimeoutSeconds(value *int32)() {
    m.http_idle_timeout_seconds = value
}
// SetId sets the id property value. A unique ID that can be used to identify and reference a load balancer.
func (m *Load_balancer_base) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetIp sets the ip property value. An attribute containing the public-facing IP address of the load balancer.
func (m *Load_balancer_base) SetIp(value *string)() {
    m.ip = value
}
// SetIpv6 sets the ipv6 property value. An attribute containing the public-facing IPv6 address of the load balancer.
func (m *Load_balancer_base) SetIpv6(value *string)() {
    m.ipv6 = value
}
// SetName sets the name property value. A human-readable name for a load balancer instance.
func (m *Load_balancer_base) SetName(value *string)() {
    m.name = value
}
// SetNetwork sets the network property value. A string indicating whether the load balancer should be external or internal. Internal load balancers have no public IPs and are only accessible to resources on the same VPC network. This property cannot be updated after creating the load balancer.
func (m *Load_balancer_base) SetNetwork(value *Load_balancer_base_network)() {
    m.network = value
}
// SetNetworkStack sets the network_stack property value. A string indicating whether the load balancer will support IPv4 or both IPv4 and IPv6 networking. This property cannot be updated after creating the load balancer.
func (m *Load_balancer_base) SetNetworkStack(value *Load_balancer_base_network_stack)() {
    m.network_stack = value
}
// SetProjectId sets the project_id property value. The ID of the project that the load balancer is associated with. If no ID is provided at creation, the load balancer associates with the user's default project. If an invalid project ID is provided, the load balancer will not be created.
func (m *Load_balancer_base) SetProjectId(value *string)() {
    m.project_id = value
}
// SetRedirectHttpToHttps sets the redirect_http_to_https property value. A boolean value indicating whether HTTP requests to the load balancer on port 80 will be redirected to HTTPS on port 443.
func (m *Load_balancer_base) SetRedirectHttpToHttps(value *bool)() {
    m.redirect_http_to_https = value
}
// SetSize sets the size property value. This field has been replaced by the `size_unit` field for all regions except in AMS2, NYC2, and SFO1. Each available load balancer size now equates to the load balancer having a set number of nodes.* `lb-small` = 1 node* `lb-medium` = 3 nodes* `lb-large` = 6 nodesYou can resize load balancers after creation up to once per hour. You cannot resize a load balancer within the first hour of its creation.
// Deprecated: 
func (m *Load_balancer_base) SetSize(value *Load_balancer_base_size)() {
    m.size = value
}
// SetSizeUnit sets the size_unit property value. How many nodes the load balancer contains. Each additional node increases the load balancer's ability to manage more connections. Load balancers can be scaled up or down, and you can change the number of nodes after creation up to once per hour. This field is currently not available in the AMS2, NYC2, or SFO1 regions. Use the `size` field to scale load balancers that reside in these regions.
func (m *Load_balancer_base) SetSizeUnit(value *int32)() {
    m.size_unit = value
}
// SetStatus sets the status property value. A status string indicating the current state of the load balancer. This can be `new`, `active`, or `errored`.
func (m *Load_balancer_base) SetStatus(value *Load_balancer_base_status)() {
    m.status = value
}
// SetStickySessions sets the sticky_sessions property value. An object specifying sticky sessions settings for the load balancer.
func (m *Load_balancer_base) SetStickySessions(value Sticky_sessionsable)() {
    m.sticky_sessions = value
}
// SetTargetLoadBalancerIds sets the target_load_balancer_ids property value. An array containing the UUIDs of the Regional load balancers to be used as target backends for a Global load balancer.
func (m *Load_balancer_base) SetTargetLoadBalancerIds(value []string)() {
    m.target_load_balancer_ids = value
}
// SetTlsCipherPolicy sets the tls_cipher_policy property value. A string indicating the policy for the TLS cipher suites used by the load balancer. The possible values are `DEFAULT` or `STRONG`. The default value is `DEFAULT`.
func (m *Load_balancer_base) SetTlsCipherPolicy(value *Load_balancer_base_tls_cipher_policy)() {
    m.tls_cipher_policy = value
}
// SetTypeEscaped sets the type property value. A string indicating whether the load balancer should be a standard regional HTTP load balancer, a regional network load balancer that routes traffic at the TCP/UDP transport layer, or a global load balancer.
func (m *Load_balancer_base) SetTypeEscaped(value *Load_balancer_base_type)() {
    m.typeEscaped = value
}
// SetVpcUuid sets the vpc_uuid property value. A string specifying the UUID of the VPC to which the load balancer is assigned.
func (m *Load_balancer_base) SetVpcUuid(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.vpc_uuid = value
}
type Load_balancer_baseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAlgorithm()(*Load_balancer_base_algorithm)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetDisableLetsEncryptDnsRecords()(*bool)
    GetDomains()([]Domainsable)
    GetEnableBackendKeepalive()(*bool)
    GetEnableProxyProtocol()(*bool)
    GetFirewall()(Lb_firewallable)
    GetForwardingRules()([]Forwarding_ruleable)
    GetGlbSettings()(Glb_settingsable)
    GetHealthCheck()(Health_checkable)
    GetHttpIdleTimeoutSeconds()(*int32)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetIp()(*string)
    GetIpv6()(*string)
    GetName()(*string)
    GetNetwork()(*Load_balancer_base_network)
    GetNetworkStack()(*Load_balancer_base_network_stack)
    GetProjectId()(*string)
    GetRedirectHttpToHttps()(*bool)
    GetSize()(*Load_balancer_base_size)
    GetSizeUnit()(*int32)
    GetStatus()(*Load_balancer_base_status)
    GetStickySessions()(Sticky_sessionsable)
    GetTargetLoadBalancerIds()([]string)
    GetTlsCipherPolicy()(*Load_balancer_base_tls_cipher_policy)
    GetTypeEscaped()(*Load_balancer_base_type)
    GetVpcUuid()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    SetAlgorithm(value *Load_balancer_base_algorithm)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetDisableLetsEncryptDnsRecords(value *bool)()
    SetDomains(value []Domainsable)()
    SetEnableBackendKeepalive(value *bool)()
    SetEnableProxyProtocol(value *bool)()
    SetFirewall(value Lb_firewallable)()
    SetForwardingRules(value []Forwarding_ruleable)()
    SetGlbSettings(value Glb_settingsable)()
    SetHealthCheck(value Health_checkable)()
    SetHttpIdleTimeoutSeconds(value *int32)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetIp(value *string)()
    SetIpv6(value *string)()
    SetName(value *string)()
    SetNetwork(value *Load_balancer_base_network)()
    SetNetworkStack(value *Load_balancer_base_network_stack)()
    SetProjectId(value *string)()
    SetRedirectHttpToHttps(value *bool)()
    SetSize(value *Load_balancer_base_size)()
    SetSizeUnit(value *int32)()
    SetStatus(value *Load_balancer_base_status)()
    SetStickySessions(value Sticky_sessionsable)()
    SetTargetLoadBalancerIds(value []string)()
    SetTlsCipherPolicy(value *Load_balancer_base_tls_cipher_policy)()
    SetTypeEscaped(value *Load_balancer_base_type)()
    SetVpcUuid(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
}
