// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Messages_response_tool_use_block_type int

const (
    TOOL_USE_MESSAGES_RESPONSE_TOOL_USE_BLOCK_TYPE Messages_response_tool_use_block_type = iota
)

func (i Messages_response_tool_use_block_type) String() string {
    return []string{"tool_use"}[i]
}
func ParseMessages_response_tool_use_block_type(v string) (any, error) {
    result := TOOL_USE_MESSAGES_RESPONSE_TOOL_USE_BLOCK_TYPE
    switch v {
        case "tool_use":
            result = TOOL_USE_MESSAGES_RESPONSE_TOOL_USE_BLOCK_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeMessages_response_tool_use_block_type(values []Messages_response_tool_use_block_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Messages_response_tool_use_block_type) isMultiValue() bool {
    return false
}
