// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Nfs_snapshot_list_response struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The snapshots property
    snapshots []Nfs_snapshot_responseable
}
// NewNfs_snapshot_list_response instantiates a new Nfs_snapshot_list_response and sets the default values.
func NewNfs_snapshot_list_response()(*Nfs_snapshot_list_response) {
    m := &Nfs_snapshot_list_response{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateNfs_snapshot_list_responseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNfs_snapshot_list_responseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewNfs_snapshot_list_response(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Nfs_snapshot_list_response) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Nfs_snapshot_list_response) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["snapshots"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateNfs_snapshot_responseFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Nfs_snapshot_responseable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Nfs_snapshot_responseable)
                }
            }
            m.SetSnapshots(res)
        }
        return nil
    }
    return res
}
// GetSnapshots gets the snapshots property value. The snapshots property
// returns a []Nfs_snapshot_responseable when successful
func (m *Nfs_snapshot_list_response) GetSnapshots()([]Nfs_snapshot_responseable) {
    return m.snapshots
}
// Serialize serializes information the current object
func (m *Nfs_snapshot_list_response) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetSnapshots() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSnapshots()))
        for i, v := range m.GetSnapshots() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("snapshots", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Nfs_snapshot_list_response) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetSnapshots sets the snapshots property value. The snapshots property
func (m *Nfs_snapshot_list_response) SetSnapshots(value []Nfs_snapshot_responseable)() {
    m.snapshots = value
}
type Nfs_snapshot_list_responseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetSnapshots()([]Nfs_snapshot_responseable)
    SetSnapshots(value []Nfs_snapshot_responseable)()
}
