// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Opensearch_config struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Name of a managed OpenSearch cluster.
    cluster_name *string
    // A unique identifier for a managed OpenSearch cluster.
    cluster_uuid *string
    // Credentials for an OpenSearch cluster user. Optional if `cluster_uuid` is passed.
    credentials Opensearch_config_credentialsable
    // host of the OpenSearch cluster
    endpoint *string
    // A unique identifier for a configuration.
    id *string
    // OpenSearch index to send logs to.
    index_name *string
    // Number of days to retain logs in OpenSearch (default: 14)
    retention_days *int32
}
// NewOpensearch_config instantiates a new Opensearch_config and sets the default values.
func NewOpensearch_config()(*Opensearch_config) {
    m := &Opensearch_config{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateOpensearch_configFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOpensearch_configFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOpensearch_config(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Opensearch_config) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetClusterName gets the cluster_name property value. Name of a managed OpenSearch cluster.
// returns a *string when successful
func (m *Opensearch_config) GetClusterName()(*string) {
    return m.cluster_name
}
// GetClusterUuid gets the cluster_uuid property value. A unique identifier for a managed OpenSearch cluster.
// returns a *string when successful
func (m *Opensearch_config) GetClusterUuid()(*string) {
    return m.cluster_uuid
}
// GetCredentials gets the credentials property value. Credentials for an OpenSearch cluster user. Optional if `cluster_uuid` is passed.
// returns a Opensearch_config_credentialsable when successful
func (m *Opensearch_config) GetCredentials()(Opensearch_config_credentialsable) {
    return m.credentials
}
// GetEndpoint gets the endpoint property value. host of the OpenSearch cluster
// returns a *string when successful
func (m *Opensearch_config) GetEndpoint()(*string) {
    return m.endpoint
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Opensearch_config) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["cluster_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClusterName(val)
        }
        return nil
    }
    res["cluster_uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClusterUuid(val)
        }
        return nil
    }
    res["credentials"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateOpensearch_config_credentialsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCredentials(val.(Opensearch_config_credentialsable))
        }
        return nil
    }
    res["endpoint"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndpoint(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["index_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIndexName(val)
        }
        return nil
    }
    res["retention_days"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRetentionDays(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. A unique identifier for a configuration.
// returns a *string when successful
func (m *Opensearch_config) GetId()(*string) {
    return m.id
}
// GetIndexName gets the index_name property value. OpenSearch index to send logs to.
// returns a *string when successful
func (m *Opensearch_config) GetIndexName()(*string) {
    return m.index_name
}
// GetRetentionDays gets the retention_days property value. Number of days to retain logs in OpenSearch (default: 14)
// returns a *int32 when successful
func (m *Opensearch_config) GetRetentionDays()(*int32) {
    return m.retention_days
}
// Serialize serializes information the current object
func (m *Opensearch_config) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("cluster_name", m.GetClusterName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("cluster_uuid", m.GetClusterUuid())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("credentials", m.GetCredentials())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("endpoint", m.GetEndpoint())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("index_name", m.GetIndexName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("retention_days", m.GetRetentionDays())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Opensearch_config) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetClusterName sets the cluster_name property value. Name of a managed OpenSearch cluster.
func (m *Opensearch_config) SetClusterName(value *string)() {
    m.cluster_name = value
}
// SetClusterUuid sets the cluster_uuid property value. A unique identifier for a managed OpenSearch cluster.
func (m *Opensearch_config) SetClusterUuid(value *string)() {
    m.cluster_uuid = value
}
// SetCredentials sets the credentials property value. Credentials for an OpenSearch cluster user. Optional if `cluster_uuid` is passed.
func (m *Opensearch_config) SetCredentials(value Opensearch_config_credentialsable)() {
    m.credentials = value
}
// SetEndpoint sets the endpoint property value. host of the OpenSearch cluster
func (m *Opensearch_config) SetEndpoint(value *string)() {
    m.endpoint = value
}
// SetId sets the id property value. A unique identifier for a configuration.
func (m *Opensearch_config) SetId(value *string)() {
    m.id = value
}
// SetIndexName sets the index_name property value. OpenSearch index to send logs to.
func (m *Opensearch_config) SetIndexName(value *string)() {
    m.index_name = value
}
// SetRetentionDays sets the retention_days property value. Number of days to retain logs in OpenSearch (default: 14)
func (m *Opensearch_config) SetRetentionDays(value *int32)() {
    m.retention_days = value
}
type Opensearch_configable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetClusterName()(*string)
    GetClusterUuid()(*string)
    GetCredentials()(Opensearch_config_credentialsable)
    GetEndpoint()(*string)
    GetId()(*string)
    GetIndexName()(*string)
    GetRetentionDays()(*int32)
    SetClusterName(value *string)()
    SetClusterUuid(value *string)()
    SetCredentials(value Opensearch_config_credentialsable)()
    SetEndpoint(value *string)()
    SetId(value *string)()
    SetIndexName(value *string)()
    SetRetentionDays(value *int32)()
}
