// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Pgbouncer_advanced_config pGBouncer connection pooling settings
type Pgbouncer_advanced_config struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // If the automatically-created database pools have been unused this many seconds, they are freed. If 0, timeout is disabled.
    autodb_idle_timeout *int32
    // Only allows a maximum this many server connections per database (regardless of user). If 0, allows unlimited connections.
    autodb_max_db_connections *int32
    // PGBouncer pool mode
    autodb_pool_mode *Pgbouncer_advanced_config_autodb_pool_mode
    // If non-zero, automatically creates a pool of that size per user when a pool doesn't exist.
    autodb_pool_size *int32
    // List of parameters to ignore when given in startup packet.
    ignore_startup_parameters []Pgbouncer_advanced_config_ignore_startup_parameters
    // If current server connections are below this number, adds more. Improves behavior when usual load comes suddenly back after period of total inactivity. The value is effectively capped at the pool size.
    min_pool_size *int32
    // Drops server connections if they have been idle more than this many seconds.  If 0, timeout is disabled. 
    server_idle_timeout *int32
    // The pooler closes any unused server connection that has been connected longer than this amount of seconds.
    server_lifetime *int32
    // Run server_reset_query (DISCARD ALL) in all pooling modes.
    server_reset_query_always *bool
}
// NewPgbouncer_advanced_config instantiates a new Pgbouncer_advanced_config and sets the default values.
func NewPgbouncer_advanced_config()(*Pgbouncer_advanced_config) {
    m := &Pgbouncer_advanced_config{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePgbouncer_advanced_configFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePgbouncer_advanced_configFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPgbouncer_advanced_config(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Pgbouncer_advanced_config) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAutodbIdleTimeout gets the autodb_idle_timeout property value. If the automatically-created database pools have been unused this many seconds, they are freed. If 0, timeout is disabled.
// returns a *int32 when successful
func (m *Pgbouncer_advanced_config) GetAutodbIdleTimeout()(*int32) {
    return m.autodb_idle_timeout
}
// GetAutodbMaxDbConnections gets the autodb_max_db_connections property value. Only allows a maximum this many server connections per database (regardless of user). If 0, allows unlimited connections.
// returns a *int32 when successful
func (m *Pgbouncer_advanced_config) GetAutodbMaxDbConnections()(*int32) {
    return m.autodb_max_db_connections
}
// GetAutodbPoolMode gets the autodb_pool_mode property value. PGBouncer pool mode
// returns a *Pgbouncer_advanced_config_autodb_pool_mode when successful
func (m *Pgbouncer_advanced_config) GetAutodbPoolMode()(*Pgbouncer_advanced_config_autodb_pool_mode) {
    return m.autodb_pool_mode
}
// GetAutodbPoolSize gets the autodb_pool_size property value. If non-zero, automatically creates a pool of that size per user when a pool doesn't exist.
// returns a *int32 when successful
func (m *Pgbouncer_advanced_config) GetAutodbPoolSize()(*int32) {
    return m.autodb_pool_size
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Pgbouncer_advanced_config) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["autodb_idle_timeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutodbIdleTimeout(val)
        }
        return nil
    }
    res["autodb_max_db_connections"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutodbMaxDbConnections(val)
        }
        return nil
    }
    res["autodb_pool_mode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePgbouncer_advanced_config_autodb_pool_mode)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutodbPoolMode(val.(*Pgbouncer_advanced_config_autodb_pool_mode))
        }
        return nil
    }
    res["autodb_pool_size"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutodbPoolSize(val)
        }
        return nil
    }
    res["ignore_startup_parameters"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfEnumValues(ParsePgbouncer_advanced_config_ignore_startup_parameters)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Pgbouncer_advanced_config_ignore_startup_parameters, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*Pgbouncer_advanced_config_ignore_startup_parameters))
                }
            }
            m.SetIgnoreStartupParameters(res)
        }
        return nil
    }
    res["min_pool_size"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMinPoolSize(val)
        }
        return nil
    }
    res["server_idle_timeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetServerIdleTimeout(val)
        }
        return nil
    }
    res["server_lifetime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetServerLifetime(val)
        }
        return nil
    }
    res["server_reset_query_always"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetServerResetQueryAlways(val)
        }
        return nil
    }
    return res
}
// GetIgnoreStartupParameters gets the ignore_startup_parameters property value. List of parameters to ignore when given in startup packet.
// returns a []Pgbouncer_advanced_config_ignore_startup_parameters when successful
func (m *Pgbouncer_advanced_config) GetIgnoreStartupParameters()([]Pgbouncer_advanced_config_ignore_startup_parameters) {
    return m.ignore_startup_parameters
}
// GetMinPoolSize gets the min_pool_size property value. If current server connections are below this number, adds more. Improves behavior when usual load comes suddenly back after period of total inactivity. The value is effectively capped at the pool size.
// returns a *int32 when successful
func (m *Pgbouncer_advanced_config) GetMinPoolSize()(*int32) {
    return m.min_pool_size
}
// GetServerIdleTimeout gets the server_idle_timeout property value. Drops server connections if they have been idle more than this many seconds.  If 0, timeout is disabled. 
// returns a *int32 when successful
func (m *Pgbouncer_advanced_config) GetServerIdleTimeout()(*int32) {
    return m.server_idle_timeout
}
// GetServerLifetime gets the server_lifetime property value. The pooler closes any unused server connection that has been connected longer than this amount of seconds.
// returns a *int32 when successful
func (m *Pgbouncer_advanced_config) GetServerLifetime()(*int32) {
    return m.server_lifetime
}
// GetServerResetQueryAlways gets the server_reset_query_always property value. Run server_reset_query (DISCARD ALL) in all pooling modes.
// returns a *bool when successful
func (m *Pgbouncer_advanced_config) GetServerResetQueryAlways()(*bool) {
    return m.server_reset_query_always
}
// Serialize serializes information the current object
func (m *Pgbouncer_advanced_config) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("autodb_idle_timeout", m.GetAutodbIdleTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("autodb_max_db_connections", m.GetAutodbMaxDbConnections())
        if err != nil {
            return err
        }
    }
    if m.GetAutodbPoolMode() != nil {
        cast := (*m.GetAutodbPoolMode()).String()
        err := writer.WriteStringValue("autodb_pool_mode", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("autodb_pool_size", m.GetAutodbPoolSize())
        if err != nil {
            return err
        }
    }
    if m.GetIgnoreStartupParameters() != nil {
        err := writer.WriteCollectionOfStringValues("ignore_startup_parameters", SerializePgbouncer_advanced_config_ignore_startup_parameters(m.GetIgnoreStartupParameters()))
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("min_pool_size", m.GetMinPoolSize())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("server_idle_timeout", m.GetServerIdleTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("server_lifetime", m.GetServerLifetime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("server_reset_query_always", m.GetServerResetQueryAlways())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Pgbouncer_advanced_config) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAutodbIdleTimeout sets the autodb_idle_timeout property value. If the automatically-created database pools have been unused this many seconds, they are freed. If 0, timeout is disabled.
func (m *Pgbouncer_advanced_config) SetAutodbIdleTimeout(value *int32)() {
    m.autodb_idle_timeout = value
}
// SetAutodbMaxDbConnections sets the autodb_max_db_connections property value. Only allows a maximum this many server connections per database (regardless of user). If 0, allows unlimited connections.
func (m *Pgbouncer_advanced_config) SetAutodbMaxDbConnections(value *int32)() {
    m.autodb_max_db_connections = value
}
// SetAutodbPoolMode sets the autodb_pool_mode property value. PGBouncer pool mode
func (m *Pgbouncer_advanced_config) SetAutodbPoolMode(value *Pgbouncer_advanced_config_autodb_pool_mode)() {
    m.autodb_pool_mode = value
}
// SetAutodbPoolSize sets the autodb_pool_size property value. If non-zero, automatically creates a pool of that size per user when a pool doesn't exist.
func (m *Pgbouncer_advanced_config) SetAutodbPoolSize(value *int32)() {
    m.autodb_pool_size = value
}
// SetIgnoreStartupParameters sets the ignore_startup_parameters property value. List of parameters to ignore when given in startup packet.
func (m *Pgbouncer_advanced_config) SetIgnoreStartupParameters(value []Pgbouncer_advanced_config_ignore_startup_parameters)() {
    m.ignore_startup_parameters = value
}
// SetMinPoolSize sets the min_pool_size property value. If current server connections are below this number, adds more. Improves behavior when usual load comes suddenly back after period of total inactivity. The value is effectively capped at the pool size.
func (m *Pgbouncer_advanced_config) SetMinPoolSize(value *int32)() {
    m.min_pool_size = value
}
// SetServerIdleTimeout sets the server_idle_timeout property value. Drops server connections if they have been idle more than this many seconds.  If 0, timeout is disabled. 
func (m *Pgbouncer_advanced_config) SetServerIdleTimeout(value *int32)() {
    m.server_idle_timeout = value
}
// SetServerLifetime sets the server_lifetime property value. The pooler closes any unused server connection that has been connected longer than this amount of seconds.
func (m *Pgbouncer_advanced_config) SetServerLifetime(value *int32)() {
    m.server_lifetime = value
}
// SetServerResetQueryAlways sets the server_reset_query_always property value. Run server_reset_query (DISCARD ALL) in all pooling modes.
func (m *Pgbouncer_advanced_config) SetServerResetQueryAlways(value *bool)() {
    m.server_reset_query_always = value
}
type Pgbouncer_advanced_configable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAutodbIdleTimeout()(*int32)
    GetAutodbMaxDbConnections()(*int32)
    GetAutodbPoolMode()(*Pgbouncer_advanced_config_autodb_pool_mode)
    GetAutodbPoolSize()(*int32)
    GetIgnoreStartupParameters()([]Pgbouncer_advanced_config_ignore_startup_parameters)
    GetMinPoolSize()(*int32)
    GetServerIdleTimeout()(*int32)
    GetServerLifetime()(*int32)
    GetServerResetQueryAlways()(*bool)
    SetAutodbIdleTimeout(value *int32)()
    SetAutodbMaxDbConnections(value *int32)()
    SetAutodbPoolMode(value *Pgbouncer_advanced_config_autodb_pool_mode)()
    SetAutodbPoolSize(value *int32)()
    SetIgnoreStartupParameters(value []Pgbouncer_advanced_config_ignore_startup_parameters)()
    SetMinPoolSize(value *int32)()
    SetServerIdleTimeout(value *int32)()
    SetServerLifetime(value *int32)()
    SetServerResetQueryAlways(value *bool)()
}
