// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Scan_findings the results of the scan.
type Scan_findings struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The number of affected resources for the finding.
    affected_resources_count *int32
    // A description of the business impact of the finding.
    business_impact *string
    // A description of the risk associated with the finding.
    details *string
    // When the finding was discovered.
    found_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The mitigation steps to resolve the finding.
    mitigation_steps []Scan_findings_mitigation_stepsable
    // The name of the rule that triggered the finding.
    name *string
    // The unique identifier for the rule that triggered the finding.
    rule_uuid *string
    // The severity of the finding.
    severity *Scan_findings_severity
    // A description of the technical details related to the finding.
    technical_details *string
}
// NewScan_findings instantiates a new Scan_findings and sets the default values.
func NewScan_findings()(*Scan_findings) {
    m := &Scan_findings{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateScan_findingsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateScan_findingsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewScan_findings(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Scan_findings) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAffectedResourcesCount gets the affected_resources_count property value. The number of affected resources for the finding.
// returns a *int32 when successful
func (m *Scan_findings) GetAffectedResourcesCount()(*int32) {
    return m.affected_resources_count
}
// GetBusinessImpact gets the business_impact property value. A description of the business impact of the finding.
// returns a *string when successful
func (m *Scan_findings) GetBusinessImpact()(*string) {
    return m.business_impact
}
// GetDetails gets the details property value. A description of the risk associated with the finding.
// returns a *string when successful
func (m *Scan_findings) GetDetails()(*string) {
    return m.details
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Scan_findings) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["affected_resources_count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAffectedResourcesCount(val)
        }
        return nil
    }
    res["business_impact"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBusinessImpact(val)
        }
        return nil
    }
    res["details"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDetails(val)
        }
        return nil
    }
    res["found_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFoundAt(val)
        }
        return nil
    }
    res["mitigation_steps"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateScan_findings_mitigation_stepsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Scan_findings_mitigation_stepsable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Scan_findings_mitigation_stepsable)
                }
            }
            m.SetMitigationSteps(res)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["rule_uuid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRuleUuid(val)
        }
        return nil
    }
    res["severity"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseScan_findings_severity)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSeverity(val.(*Scan_findings_severity))
        }
        return nil
    }
    res["technical_details"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTechnicalDetails(val)
        }
        return nil
    }
    return res
}
// GetFoundAt gets the found_at property value. When the finding was discovered.
// returns a *Time when successful
func (m *Scan_findings) GetFoundAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.found_at
}
// GetMitigationSteps gets the mitigation_steps property value. The mitigation steps to resolve the finding.
// returns a []Scan_findings_mitigation_stepsable when successful
func (m *Scan_findings) GetMitigationSteps()([]Scan_findings_mitigation_stepsable) {
    return m.mitigation_steps
}
// GetName gets the name property value. The name of the rule that triggered the finding.
// returns a *string when successful
func (m *Scan_findings) GetName()(*string) {
    return m.name
}
// GetRuleUuid gets the rule_uuid property value. The unique identifier for the rule that triggered the finding.
// returns a *string when successful
func (m *Scan_findings) GetRuleUuid()(*string) {
    return m.rule_uuid
}
// GetSeverity gets the severity property value. The severity of the finding.
// returns a *Scan_findings_severity when successful
func (m *Scan_findings) GetSeverity()(*Scan_findings_severity) {
    return m.severity
}
// GetTechnicalDetails gets the technical_details property value. A description of the technical details related to the finding.
// returns a *string when successful
func (m *Scan_findings) GetTechnicalDetails()(*string) {
    return m.technical_details
}
// Serialize serializes information the current object
func (m *Scan_findings) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("affected_resources_count", m.GetAffectedResourcesCount())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("business_impact", m.GetBusinessImpact())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("details", m.GetDetails())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("found_at", m.GetFoundAt())
        if err != nil {
            return err
        }
    }
    if m.GetMitigationSteps() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetMitigationSteps()))
        for i, v := range m.GetMitigationSteps() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("mitigation_steps", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("rule_uuid", m.GetRuleUuid())
        if err != nil {
            return err
        }
    }
    if m.GetSeverity() != nil {
        cast := (*m.GetSeverity()).String()
        err := writer.WriteStringValue("severity", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("technical_details", m.GetTechnicalDetails())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Scan_findings) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAffectedResourcesCount sets the affected_resources_count property value. The number of affected resources for the finding.
func (m *Scan_findings) SetAffectedResourcesCount(value *int32)() {
    m.affected_resources_count = value
}
// SetBusinessImpact sets the business_impact property value. A description of the business impact of the finding.
func (m *Scan_findings) SetBusinessImpact(value *string)() {
    m.business_impact = value
}
// SetDetails sets the details property value. A description of the risk associated with the finding.
func (m *Scan_findings) SetDetails(value *string)() {
    m.details = value
}
// SetFoundAt sets the found_at property value. When the finding was discovered.
func (m *Scan_findings) SetFoundAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.found_at = value
}
// SetMitigationSteps sets the mitigation_steps property value. The mitigation steps to resolve the finding.
func (m *Scan_findings) SetMitigationSteps(value []Scan_findings_mitigation_stepsable)() {
    m.mitigation_steps = value
}
// SetName sets the name property value. The name of the rule that triggered the finding.
func (m *Scan_findings) SetName(value *string)() {
    m.name = value
}
// SetRuleUuid sets the rule_uuid property value. The unique identifier for the rule that triggered the finding.
func (m *Scan_findings) SetRuleUuid(value *string)() {
    m.rule_uuid = value
}
// SetSeverity sets the severity property value. The severity of the finding.
func (m *Scan_findings) SetSeverity(value *Scan_findings_severity)() {
    m.severity = value
}
// SetTechnicalDetails sets the technical_details property value. A description of the technical details related to the finding.
func (m *Scan_findings) SetTechnicalDetails(value *string)() {
    m.technical_details = value
}
type Scan_findingsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAffectedResourcesCount()(*int32)
    GetBusinessImpact()(*string)
    GetDetails()(*string)
    GetFoundAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetMitigationSteps()([]Scan_findings_mitigation_stepsable)
    GetName()(*string)
    GetRuleUuid()(*string)
    GetSeverity()(*Scan_findings_severity)
    GetTechnicalDetails()(*string)
    SetAffectedResourcesCount(value *int32)()
    SetBusinessImpact(value *string)()
    SetDetails(value *string)()
    SetFoundAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetMitigationSteps(value []Scan_findings_mitigation_stepsable)()
    SetName(value *string)()
    SetRuleUuid(value *string)()
    SetSeverity(value *Scan_findings_severity)()
    SetTechnicalDetails(value *string)()
}
