// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Suppressed_resource_root_links_pages struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The first property
    first *string
    // The last property
    last *string
    // The next property
    next *string
    // The prev property
    prev *string
}
// NewSuppressed_resource_root_links_pages instantiates a new Suppressed_resource_root_links_pages and sets the default values.
func NewSuppressed_resource_root_links_pages()(*Suppressed_resource_root_links_pages) {
    m := &Suppressed_resource_root_links_pages{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSuppressed_resource_root_links_pagesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSuppressed_resource_root_links_pagesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSuppressed_resource_root_links_pages(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Suppressed_resource_root_links_pages) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Suppressed_resource_root_links_pages) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["first"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFirst(val)
        }
        return nil
    }
    res["last"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLast(val)
        }
        return nil
    }
    res["next"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNext(val)
        }
        return nil
    }
    res["prev"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPrev(val)
        }
        return nil
    }
    return res
}
// GetFirst gets the first property value. The first property
// returns a *string when successful
func (m *Suppressed_resource_root_links_pages) GetFirst()(*string) {
    return m.first
}
// GetLast gets the last property value. The last property
// returns a *string when successful
func (m *Suppressed_resource_root_links_pages) GetLast()(*string) {
    return m.last
}
// GetNext gets the next property value. The next property
// returns a *string when successful
func (m *Suppressed_resource_root_links_pages) GetNext()(*string) {
    return m.next
}
// GetPrev gets the prev property value. The prev property
// returns a *string when successful
func (m *Suppressed_resource_root_links_pages) GetPrev()(*string) {
    return m.prev
}
// Serialize serializes information the current object
func (m *Suppressed_resource_root_links_pages) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("first", m.GetFirst())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("last", m.GetLast())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("next", m.GetNext())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("prev", m.GetPrev())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Suppressed_resource_root_links_pages) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFirst sets the first property value. The first property
func (m *Suppressed_resource_root_links_pages) SetFirst(value *string)() {
    m.first = value
}
// SetLast sets the last property value. The last property
func (m *Suppressed_resource_root_links_pages) SetLast(value *string)() {
    m.last = value
}
// SetNext sets the next property value. The next property
func (m *Suppressed_resource_root_links_pages) SetNext(value *string)() {
    m.next = value
}
// SetPrev sets the prev property value. The prev property
func (m *Suppressed_resource_root_links_pages) SetPrev(value *string)() {
    m.prev = value
}
type Suppressed_resource_root_links_pagesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFirst()(*string)
    GetLast()(*string)
    GetNext()(*string)
    GetPrev()(*string)
    SetFirst(value *string)()
    SetLast(value *string)()
    SetNext(value *string)()
    SetPrev(value *string)()
}
